
(()=>{'use strict';
 const E=id=>document.getElementById(id),all=(s,r=document)=>[...r.querySelectorAll(s)],safe=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 const flowCfg={mode:'smart',speed:'normal',cell:115,maxCell:4,zeroThreshold:.15};
 const restored=new Set();
 const originalRestored=window.YTBS_V53?.isTerminalRestored?.bind(window.YTBS_V53);
 if(window.YTBS_V53){window.YTBS_V53.isTerminalRestored=id=>restored.has(String(id))||(originalRestored?originalRestored(id):false);}
 function currentSet(){return typeof resultSet==='function'?resultSet():null;}
 function pathLength(px){let n=0;for(let i=1;i<px.length;i++)n+=Math.hypot(px[i][0]-px[i-1][0],px[i][1]-px[i-1][1]);return n;}
 function loadingPct(line){try{const season=E('v4Season')?.value||'nominal';const out=window.LineCapacityEngine?.loading?.(line,season);return Number.isFinite(out?.percent)?out.percent:null;}catch(_){return null;}}
 function speedFactor(load){const mult={slow:.72,normal:1,fast:1.35}[flowCfg.speed]||1;if(!Number.isFinite(load))return .78*mult;return (.52+clamp(load,0,120)/120*1.15)*mult;}
 function baseCount(len,load,selected){if(len<34)return selected?1:0;let n=len<120?1:len<300?2:3;if(Number.isFinite(load)){if(load<25)n=1;else if(load>=90&&n>0)n=Math.min(3,n+1);}if(selected)n=Math.max(1,n);return Math.min(3,n);}
 function arrowPoints(points,count,direction,lineLoad){if(count<=0||points.length<2)return[];let lens=[],total=0;for(let i=1;i<points.length;i++){let d=Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]);lens.push(d);total+=d;}if(total<18)return[];const now=performance.now()/1000,phase=(now*36*speedFactor(lineLoad))%(total/count);let out=[];for(let k=0;k<count;k++){let z=(k*total/count+phase)%(total);if(direction<0)z=total-z;let i=0;while(i<lens.length-1&&z>lens[i]){z-=lens[i];i++;}let a=points[i],b=points[i+1],t=lens[i]?z/lens[i]:0;out.push({x:a[0]+(b[0]-a[0])*t,y:a[1]+(b[1]-a[1])*t,ang:Math.atan2((b[1]-a[1])*direction,(b[0]-a[0])*direction)});}return out;}
 function paintArrow(g,p,selected=false){g.save();g.translate(p.x,p.y);g.rotate(p.ang);g.fillStyle=selected?'#fff0aa':'#ffe2a2';g.strokeStyle=selected?'#174056':'#263441';g.lineWidth=selected?1.7:1;g.beginPath();g.moveTo(8,0);g.lineTo(-6,-4.5);g.lineTo(-3.5,0);g.lineTo(-6,4.5);g.closePath();g.fill();g.stroke();g.restore();}
 function visibleSmartLines(candidates,set){const rows=[];for(const item of candidates){if(item.type!=='line'||v4LineOut(item.l))continue;const dir=flowDirection(item.l,set);if(!dir)continue;const p=latestResult('ElmLne',item.l.FID,'P','from');if(!p||Math.abs(Number(p.value)||0)<flowCfg.zeroThreshold)continue;const len=pathLength(item.px),load=loadingPct(item.l),selected=item.l.FID===selectedLine,count=baseCount(len,load,selected);if(!count)continue;rows.push({item,dir,len,load,selected,count,priority:(selected?1e9:0)+(Number.isFinite(load)?load*1000:0)+len});}rows.sort((a,b)=>b.priority-a.priority);return rows;}
 const originalRender=window.renderResultOverlay;
 window.renderResultOverlay=function(animate){if(currentView!=='map'||mapMode!=='geo')return;let cn=getOverlayCanvas(),g=cn.getContext('2d'),dpr=cn.width/Math.max(mapCam.w,1);g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,mapCam.w,mapCam.h);const set=currentSet(),metric=E('mapMetric').value;if(!active||!set)return;let candidates=collectOverlayCandidates();v2.overlayCandidates=candidates;
  if(metric==='V'&&!E('mapLabels').checked){for(const item of candidates){if(item.type!=='bus')continue;let nom=Number(active.get('ElmTerm',item.r.id)?.uknom),p=nom>0?item.r.value/nom:null;g.beginPath();g.arc(item.x,item.y,8,0,2*Math.PI);g.fillStyle=p===null?'#9eaabe':p<.95?'#a38cec':p>1.05?'#ec8b83':'#62d5b4';g.fill();g.strokeStyle='#10283a';g.lineWidth=1;g.stroke();}}
  if(E('mapLabels').checked||selectedLine){for(const item of candidates){if(item.type==='bus'){let nominal=Number(active.get('ElmTerm',item.r.id)?.uknom),pu=nominal>0?` / ${(item.r.value/nominal).toFixed(3)} pu`:'';let ratio=nominal>0?item.r.value/nominal:null;g.beginPath();g.arc(item.x,item.y,9,0,2*Math.PI);g.fillStyle=ratio===null?'#9eaabe':ratio<.95?'#a38cec':ratio>1.05?'#ec8b83':'#62d5b4';g.globalAlpha=.95;g.fill();g.strokeStyle='#10283a';g.lineWidth=1.7;g.stroke();g.globalAlpha=1;paintBadge(g,`${item.site.loc_name.slice(0,13)}: ${fmt(item.r.value)} kV${pu}`,item.x,item.y-11);}else if(metric!=='quality'&&(E('mapLabels').checked||item.l.FID===selectedLine)){paintBadge(g,`${fmt(item.val.value)} ${item.val.unit}`,item.mid[0],item.mid[1]-5);}}}
  if(animate&&E('mapFlow').checked&&metric!=='V'){
   const grid=new Map(),cell=flowCfg.cell,maxCell=flowCfg.mode==='detail'?7:flowCfg.maxCell;let drawnLines=0,drawnArrows=0;
   for(const row of visibleSmartLines(candidates,set)){
    let wanted=row.count,accepted=0;const pts=arrowPoints(row.item.px,wanted,row.dir,row.load);for(const p of pts){const key=Math.floor(p.x/cell)+'|'+Math.floor(p.y/cell),used=grid.get(key)||0;if(!row.selected&&flowCfg.mode==='smart'&&used>=maxCell)continue;grid.set(key,used+1);paintArrow(g,p,row.selected);accepted++;drawnArrows++;}if(accepted)drawnLines++;
   }
   const s=E('v55FlowStatus');if(s)s.textContent=`Akış: ${drawnLines} hat · ${drawnArrows} ok · hat başına ≤3`;
  }
 };
 // startFlow already schedules overlay refresh; adaptive speed is computed per line in render.
 function addAnimationControls(){const host=E('v54FilterExtra')||E('v42MapAside');if(!host||E('v55AnimControls'))return;const box=document.createElement('div');box.id='v55AnimControls';box.innerHTML=`<div class="sectiontitle">AKIŞ ANİMASYONU</div><label>Yoğunluk <select id="v55FlowMode"><option value="smart">Akıllı (varsayılan)</option><option value="detail">Ayrıntılı</option></select></label><label>Görsel hız <select id="v55FlowSpeed"><option value="slow">Yavaş</option><option value="normal" selected>Normal</option><option value="fast">Hızlı</option></select></label><label>Hücre yoğunluğu <input id="v55Density" type="range" min="2" max="7" step="1" value="4"><span id="v55DensityVal">4</span></label><p class="mini">Ok sayısı görünür hat uzunluğu ve yüklenmeye göre 0–3 arasında seçilir. Türkiye geneli görünümde yoğun hücreler otomatik sadeleştirilir; seçili hat önceliklidir.</p>`;host.append(box);E('v55FlowMode').onchange=e=>{flowCfg.mode=e.target.value;renderResultOverlay(false);};E('v55FlowSpeed').onchange=e=>flowCfg.speed=e.target.value;E('v55Density').oninput=e=>{flowCfg.maxCell=Number(e.target.value);E('v55DensityVal').textContent=e.target.value;};const bar=E('v54Toolbar');if(bar&&!E('v55FlowStatus')){const s=document.createElement('span');s.id='v55FlowStatus';s.textContent='Akış: sonuç bekleniyor';bar.append(s);}}
 // -------- Virtual energization diagnostics --------
 function terminalOfCub(cub){return String(active?.get('StaCubic',String(cub||''))?.fold_id||'')||null;}
 function switchGraph(){const adj=new Map(),add=(a,b,sw)=>{if(!a||!b)return;if(!adj.has(a))adj.set(a,[]);adj.get(a).push({to:b,sw});};for(let i=0;i<(active?.t('ElmCoup')?.Values.length||0);i++){const sw=active.row('ElmCoup',i),a=terminalOfCub(sw.bus1),b=terminalOfCub(sw.bus2);if(!a||!b)continue;add(a,b,sw);add(b,a,sw);}return adj;}
 function traceEnd(start,maxDepth=14){const adj=switchGraph(),q=[{t:start,path:[],terms:[start]}],seen=new Set([start]),candidates=[];while(q.length){const cur=q.shift(),term=active.get('ElmTerm',cur.t);if(cur.path.length>0&&term&&Number(term.outserv)!==1)candidates.push(cur);if(cur.path.length>=maxDepth)continue;for(const e of adj.get(cur.t)||[]){if(seen.has(e.to))continue;seen.add(e.to);q.push({t:e.to,path:[...cur.path,e.sw],terms:[...cur.terms,e.to]});}}candidates.sort((a,b)=>a.path.length-b.path.length);return candidates[0]||null;}
 function analyzeLine(line){if(!active||!line)return null;const ends=['bus1','bus2'].map(k=>terminalOfCub(line[k]));const sides=ends.map(t=>{const target=t?traceEnd(t):null;return {start:t,target:target?.t||null,terms:target?.terms||[t].filter(Boolean),switches:(target?.path||[]).map(sw=>({id:sw.FID,name:sw.loc_name,on:Number(v42.switchOverrides.has(sw.FID)?v42.switchOverrides.get(sw.FID):sw.on_off),out:Number(sw.outserv)||0})),found:!!target};});const proposedTerms=[...new Set(sides.flatMap(s=>s.terms).filter(t=>t&&Number(active.get('ElmTerm',t)?.outserv)===1))],proposedSwitches=[...new Map(sides.flatMap(s=>s.switches).filter(s=>s.on!==1||s.out===1).map(s=>[s.id,s])).values()];return {line:line.FID,originalOut:Number(line.outserv)||0,scenarioOut:v4LineOut(line)?1:0,ends,sides,proposedTerms,proposedSwitches,connectable:sides.every(s=>s.found),warnings:proposedSwitches.filter(s=>s.out===1).map(s=>s.id+' anahtarı servis dışı')};}
 function applyPlan(plan){if(!plan)return false;const ok=ScenarioController.applyBundle({line:plan.line,lineOff:0,switches:plan.proposedSwitches,restoredTerminals:plan.proposedTerms});try{drawMap();}catch(_){}renderEnergization();return ok;}
 function resetVirtual(){if(!restored.size)return;restored.clear();ScenarioController.touch();renderEnergization();}
 function renderEnergization(){const target=E('v54CurrentStatus')||E('v43Body');if(!target)return;target.querySelector('#v55Energization')?.remove();const line=selectedLine&&active?.lineById(selectedLine);if(!line)return;const p=analyzeLine(line),box=document.createElement('section');box.id='v55Energization';box.className='v55Diag';const scenarioChanged=v4.overrides.has(line.FID)&&Number(v4.overrides.get(line.FID))===0&&Number(line.outserv)===1;let status=scenarioChanged?'Sanal olarak servise alındı':v4LineOut(line)?'Servis dışı':'Serviste';const swOpen=p.proposedSwitches.filter(s=>s.out!==1).length,swOut=p.proposedSwitches.filter(s=>s.out===1).length;box.innerHTML=`<h4>⚡ Sanal devreye alma analizi</h4><div class="row"><span>Hat durumu</span><b>${safe(status)}</b></div><div class="row"><span>Uç bağlantı yolu</span><b class="${p.connectable?'ok':'bad'}">${p.connectable?'Çözümlendi':'Eksik'}</b></div><div class="row"><span>Servis dışı terminaller</span><b>${p.proposedTerms.length}</b></div><div class="row"><span>Kapatılması önerilen açık anahtar</span><b>${swOpen}</b></div><div class="row"><span>Servis dışı anahtar</span><b class="${swOut?'warn':'ok'}">${swOut}</b></div><p class="mini">Bu yalnız sanal statik topoloji analizidir. Anahtar önerileri gerçek işletme talimatı değildir; servis dışı anahtarlar otomatik etkinleştirilmez.</p>${Number(line.outserv)===1?`<button id="v55ApplyPlan" class="sm" ${p.connectable?'':'disabled'}>${p.connectable?'Sanal bağlantı planını senaryoya uygula':'Bağlantı planı tamamlanamadı'}</button>`:''}`;target.append(box);E('v55ApplyPlan')?.addEventListener('click',()=>{if(!p.connectable){alert('Her iki uç için servis içi elektriksel hedef çözümlenemedi.');return;}applyPlan(p);});}
 const oldSelect=window.selectLine;window.selectLine=function(id){const r=oldSelect.apply(this,arguments);setTimeout(renderEnergization,0);return r;};
 const oldReset=ScenarioController.reset;ScenarioController.reset=function(...args){restored.clear();const r=oldReset.apply(this,args);setTimeout(renderEnergization,0);return r;};
 const oldUndo=ScenarioController.undo;ScenarioController.undo=function(...args){const r=oldUndo.apply(this,args);setTimeout(renderEnergization,0);return r;};
 // -------- Newton diagnostics only; never relabel fallback as NR success --------
 function solverDiag(){const s=v3?.solver;if(!s)return null;const sum=s.summary||[];return {islands:sum.length,nrAccepted:sum.filter(x=>x.status==='CONVERGED_NR_EXPERIMENTAL').length,nrFallback:sum.filter(x=>x.nrFallback).length,reasons:[...new Set(sum.map(x=>x.reason).filter(Boolean))],findings:s.findings||{}};}
 function addNewtonDiag(){const a=E('view-analysis');if(!a||E('v55NewtonDiag'))return;const d=document.createElement('details');d.id='v55NewtonDiag';d.innerHTML='<summary>v5.5 Newton / model tanısı</summary><pre id="v55NewtonText">Hesap sonucu bekleniyor.</pre>';a.prepend(d);}
 const oldApplyComputed=window.applyComputedIslands;window.applyComputedIslands=function(...args){const r=oldApplyComputed.apply(this,args);const d=solverDiag(),t=E('v55NewtonText');if(t)t.textContent=d?JSON.stringify(d,null,2):'Tanı yok';return r;};
 function version(){document.title='YTBS | Şebeke Görüntüleyici v5.5';const h=document.querySelector('.apphead h1');if(h)h.textContent='YTBS Şebeke Görüntüleyici v5.5';if(E('footerRight'))E('footerRight').textContent='YTBS · Tek HTML · v5.5 · akıllı akış animasyonu · deneysel AC/DC';}
 function init(){addAnimationControls();addNewtonDiag();version();if(window.INFO){INFO.map+='<h3>v5.5 · Akıllı akış animasyonu</h3><p>Akış okları görünür hat uzunluğu, geçerli yüklenme, yakınlaştırma ve ekran yoğunluğuna göre 0–3 arasında seçilir. Ok hızı yüklenmeye göre görsel olarak ölçeklenir; fiziksel iletim hızı değildir. Türkiye geneli görünümde hücre bazlı yoğunluk sınırlaması uygulanır.</p>';INFO.metrics+='<h3>v5.5 · Sanal devreye alma</h3><p>Başlangıçta servis dışı hatlarda yalnız hat outserv değerinin değiştirilmesi başarı sayılmaz. Uç terminal ve anahtar yolları ayrı analiz edilir; genel yük akışı yakınsasa dahi seçilen hat için geçerli terminal P/Q sonucu ayrıca doğrulanır.</p>';}}
 init();
 window.SmartFlowAnimationEngine={config:flowCfg,visible:()=>{const s=currentSet();return s?visibleSmartLines(collectOverlayCandidates(),s).map(x=>({id:x.item.l.FID,length:x.len,loading:x.load,count:x.count,selected:x.selected})):[];},maxPerLine:3};
 window.VirtualEnergizationEngine={analyze:id=>analyzeLine(active?.lineById(id)),apply:id=>applyPlan(analyzeLine(active?.lineById(id))),restored:()=>[...restored],restore:items=>{restored.clear();for(const id of items||[])restored.add(String(id));refreshRestoredEnds();renderEnergization();},reset:resetVirtual};
 window.YTBS_V55_TEST={flow:()=>({config:{...flowCfg},maxPerLine:3,visible:window.SmartFlowAnimationEngine.visible()}),energization:id=>window.VirtualEnergizationEngine.analyze(id),restored:()=>[...restored],solver:solverDiag,version:'5.5'};
})();

// Narrow compatibility bridge for the modular v6 shell. All original v5.5 UI and
// electrical behavior remains owned by the legacy modules during phase 1.
window.V6Legacy = {
  getActive: () => active,
  getSolver: () => v3.solver,
  getResultSets: () => v2.sets,
  getScenario: () => ({lines: [...v4.overrides], switches: [...v42.switchOverrides], restoredTerminals: window.VirtualEnergizationEngine?.restored?.()||[], autoRestoreTerminals: !!document.getElementById('v53AutoTerm')?.checked, revision: window.ScenarioController?.revision}),
  restoreScenario: snapshot => window.ScenarioController?.restore(snapshot),
  runAnalysis: () => startV3Solver(),
  loadFiles: files => loadFiles(files),
  openView: name => setView(name),
  addCalculatedResult: (name, rows, metadata) => {
    if (!active) return;
    const set = newDgsResultSet('calculation', name, rows, metadata);
    v2.sets.push(set);
    v2.selectedSet = set.id;
    listSets();
    if (currentView === 'analysis') renderAnalysis();
    if (currentView === 'map') drawMap();
  },
};
