
/* v4.1: Tek DGS modeli üzerinde yerel, geri alınabilir görselleştirme ve senaryo katmanı. */
const v4={activeOverrides:null,overrides:new Map(),capacities:new Map(),styles:new Map(),thresholds:[50,80,90,100],base:null,baseSolver:null,scenario:null,scenarioSolver:null,generation:0,hoverTimer:0,parallel:new Map(),validation:null};
cfg.v4Geometry='detailed';
function v4LineOut(line){return (v4.activeOverrides?.has(line.FID)?v4.activeOverrides.get(line.FID):line.outserv)===1;}
function v4ComputeParallel(){v4.parallel.clear();if(!active)return;let byPair=new Map();for(const l of active.lines){const key=[l.stationA,l.stationB].sort().join('|');if(!l.stationA||!l.stationB)continue;let ls=byPair.get(key);if(!ls){ls=[];byPair.set(key,ls);}ls.push(l);}for(const ls of byPair.values())for(let i=0;i<ls.length;i++)v4.parallel.set(ls[i].FID,{index:i,count:ls.length});}
function v4LinePixels(line,points){let px=points.map(p=>coordsToPx(p[1],p[0]));if(cfg.v4Geometry!=='simple'||px.length!==2)return px;let info=v4.parallel.get(line.FID);if(!info||info.count<2)return px;const a=px[0],b=px[1],dx=b[0]-a[0],dy=b[1]-a[1],length=Math.hypot(dx,dy);if(length<.01)return px;const orientation=line.stationA<line.stationB?1:-1,offset=(info.index-(info.count-1)/2)*Math.max(4,2+v4VoltStyle(line).width)*orientation;return [[a[0]-dy/length*offset,a[1]+dx/length*offset],[b[0]-dy/length*offset,b[1]+dx/length*offset]];}
function v4VoltStyle(line){return v4.styles.get(String(line.voltage))||{color:VOLT_COLORS[line.voltage]||VOLT_COLORS.other,width:cfg.lineWidth};}
function v4Notify(msg,bad=false){const el=$('v4ScenarioStatus');if(el){el.textContent=msg;el.className='notice'+(bad?' warn':'');}}
function v4PopulateStations(){const opts=['<option value="">Trafo merkezi seçiniz</option>',...(active?.sites||[]).map(x=>`<option value="${h(x.FID)}">${h(x.loc_name)} (${h(x.FID)})</option>`)];$('sldStation').innerHTML=opts.join('');$('sldStation').value=selectedSite||'';}
function v4RenderStyles(){const vs=active?Array.from(new Set(active.lines.map(x=>String(x.voltage??'other')))).sort((a,b)=>Number(b)-Number(a)):['400','154','66','other'];const tbody=$('v4VoltageSettings');tbody.innerHTML=vs.map(k=>{let old=v4.styles.get(k)||{color:VOLT_COLORS[k]||VOLT_COLORS.other,width:cfg.lineWidth};v4.styles.set(k,old);return `<tr><td>${h(k)}</td><td><input type="color" data-v4color="${h(k)}" value="${h(old.color)}" aria-label="${h(k)} kV renk"></td><td><input style="width:83px" type="number" min="0.5" max="12" step="0.5" data-v4width="${h(k)}" value="${old.width}" aria-label="${h(k)} kV çizgi kalınlığı"></td></tr>`;}).join('');
 tbody.querySelectorAll('[data-v4color]').forEach(input=>input.oninput=()=>{const k=input.dataset.v4color;v4.styles.get(k).color=input.value;VOLT_COLORS[k]=input.value;drawMap();});
 tbody.querySelectorAll('[data-v4width]').forEach(input=>input.oninput=()=>{const k=input.dataset.v4width;let val=Number(input.value);if(val>=.5&&val<=12)v4.styles.get(k).width=val;drawMap();});}
function v4ScenarioLine(){const q=norm($('v4ScenarioLine').value.trim());if(!active||!q)return null;return active.lines.find(x=>norm(x.FID)===q)||active.lines.find(x=>norm(x.loc_name).includes(q));}
function v4OverlayStatus(){if(!active)return;const changed=[...v4.overrides].filter(([id,v])=>active.lineById(id)?.outserv!==v);const text=changed.length?`${changed.length} sanal hat durumu değiştirildi: ${changed.slice(0,10).map(([id,v])=>id+':'+(v?'servis dışı':'serviste')).join(', ')}. Orijinal DGS modeli değişmedi.`:'Senaryoda değişiklik yok; orijinal JSON değiştirilmedi.';v4Notify(text);let s=$('v4MapStatus');if(s)s.textContent=text;if(currentView==='sld')v4SldInfo();}
function v4Loading(line){let cap=v4.capacities.get(line.FID),season=$('v4Season').value;if(!cap||!Number.isFinite(cap[season])||cap[season]<=0)return null;if(v4LineOut(line))return null;
 let ends=['from','to'].map(end=>({p:latestResult('ElmLne',line.FID,'P',end),q:latestResult('ElmLne',line.FID,'Q',end)})).filter(x=>x.p&&x.q&&x.p.quality!=='INVALID'&&x.q.quality!=='INVALID'&&Math.abs(new Date(x.p.timestamp)-new Date(x.q.timestamp))<120001);
 if(!ends.length)return null;let e=ends.sort((a,b)=>Math.hypot(b.p.value,b.q.value)-Math.hypot(a.p.value,a.q.value))[0];return {percent:100*Math.hypot(e.p.value,e.q.value)/cap[season],p:e.p.value,q:e.q.value,capacity:cap[season],source:e.p.source,season};}
function v4ValidateCalc(){if(!active)return;let txt='Doğrulama durumu: BU MODEL İÇİN BAĞIMSIZ ELEKTRİKSEL REFERANS TESTİ YOK. AC-PQ sonucu deneyseldir; yakınsama, doğruluk kanıtı değildir.';let result={status:'NOT_VALIDATED'};
 if(String(active.timeKey).startsWith('202609231200')&&!v4.overrides.size&&resultSet()?.kind==='calculation'){
 const pairs=[['B9466','ÜRGÜP 400 kV bara',412.72,latestResult('ElmTerm','B9466','V')?.value,'kV',5],['H5846','ÜRGÜP–ELBİSTAN TES hat başlangıç P',-526.87,latestResult('ElmLne','H5846','P','from')?.value,'MW',30],['H5713','SİNCAN–ÜRGÜP-I hat başlangıç P',-470.84,latestResult('ElmLne','H5713','P','from')?.value,'MW',30]];
 result={status:'FAILED',samples:pairs.map(([id,name,reference,calc,unit,tolerance])=>({id,name,reference,calc,unit,tolerance,absoluteError:calc==null?null:Math.abs(calc-reference)}))};const failed=result.samples.filter(x=>x.absoluteError===null||x.absoluteError>x.tolerance);result.status=failed.length?'FAILED':'SAMPLE_MATCH_ONLY';txt=(failed.length?`REFERANS UYUMSUZLUĞU: ${failed.length}/${result.samples.length} örnek, mühendislik karşılaştırma eşiğini karşılamadı. Elektriksel sonuçlar doğrulanmadı.`:'Üç örnek karşılaştırması uyumlu; tüm sistem doğrulaması yapılmadı.')+' '+result.samples.map(x=>`${x.id}: Excel ${x.reference} ${x.unit}, yerel ${x.calc==null?'yok':x.calc.toFixed(2)} ${x.unit}`).join(' · ');
 }
 v4.validation=result;for(const id of ['v4ValidationMap','v4ValidationAnalysis']){const el=$(id);if(el){el.textContent=txt;el.className='notice '+(result.status==='FAILED'?'bad':'warn');}}
}
const v4PriorColor=resultLineColor;resultLineColor=function(line){if($('mapMetric')?.value==='inventory')return v4VoltStyle(line).color;if($('mapMetric')?.value!=='loading')return v4PriorColor(line);let a=v4Loading(line);if(!a)return '#74889e';const [a0,a1,a2,a3]=v4.thresholds;return a.percent>a3?'#f16373':a.percent>a2?'#ffad5e':a.percent>a1?'#f7d76b':a.percent>a0?'#8cdb8a':'#54c5a0';};
const v4PreviousShow=showLine;showLine=function(line,ctx,selected=false,scale=1){return v4PreviousShow(line,ctx,selected,scale);};
const v4PreviousSetView=setView;setView=function(v){if(v==='sld'){stopFlow();currentView='sld';$$('.view').forEach(e=>e.classList.toggle('active',e.id==='view-sld'));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view==='sld'));mapMode='scheme';$('schemeMode').classList.remove('hidden');v4PopulateStations();if(!selectedSite&&active?.sites?.length){let first=active.sites.find(s=>s.FID===$('mapSite').value)||active.sites[0];selectSite(first.FID);}requestAnimationFrame(()=>{drawScheme();v4SldInfo();});return;}if(v==='map'){mapMode='geo';$('geoMode').classList.remove('hidden');$('schemeMode').classList.add('hidden');}v4PreviousSetView(v);};
const v4PreviousMapMode=setMapMode;setMapMode=function(mode){if(mode==='scheme'){setView('sld');return;}if(currentView==='sld'){setView('map');return;}v4PreviousMapMode(mode);};
$('sldHost').appendChild($('schemeMode'));$('v4SldLevel').onchange=()=>drawScheme();$('sldStation').onchange=()=>{const id=$('sldStation').value;if(!id)return;selectSite(id);drawScheme();v4SldInfo();};
$('sldLineOff').onclick=()=>{const id=$('sldLine').value;if(id){v4Apply(id,1);drawScheme();}else v4Notify('Önce SLD bağlı hat listesinden hat seçiniz.',true);};$('sldLineOn').onclick=()=>{const id=$('sldLine').value;if(id){v4Apply(id,0);drawScheme();}else v4Notify('Önce SLD bağlı hat listesinden hat seçiniz.',true);};$('sldFromMap').onclick=()=>{const id=selectedSite||$('sldStation').value;setView('map');if(id)focusSite(id);};
$('sldDownload').onclick=()=>{const svg=$('schemeSvg');if(!svg.childElementCount){v4Notify('SVG şeması henüz oluşturulmadı.',true);return;}downloadText(new XMLSerializer().serializeToString(svg),'YTBS_SLD_'+(selectedSite||'TM')+'.svg','image/svg+xml;charset=utf-8');};
function v4SldInfo(){if(!active)return;const site=active.siteById(selectedSite||$('sldStation').value),el=$('sldInfo');if(!site){el.textContent='TM seçiniz.';return;}const lines=active.stationLines.get(site.FID)||[];let select=$('sldLine'),old=select.value;select.innerHTML='<option value="">Hat seçiniz</option>'+lines.map(l=>`<option value="${h(l.FID)}">${h(l.FID)} ${h(l.loc_name.slice(0,33))}</option>`).join('');select.value=lines.some(l=>l.FID===old)?old:'';el.innerHTML=`<div class="sectiontitle">${h(site.loc_name)} · Modelden gerçek hat referansları · ${lines.length} hat</div><div class="chips">${lines.slice(0,80).map(l=>`<button class="sm" data-v4sl="${h(l.FID)}">${h(l.FID)} ${h(l.loc_name.slice(0,35))} · ${v4LineOut(l)?'SERVİS DIŞI':'serviste'}</button>`).join('')}</div><p class="mini">Ana şema otomatik yerleşimli özet/fider grafıdır. DGS'de mevcut olmayan özgün PowerFactory çizim koordinatları ve kesici sembolleri üretilmez.</p>`;el.querySelectorAll('[data-v4sl]').forEach(b=>b.onclick=()=>{const l=active.lineById(b.dataset.v4sl);$('v4ScenarioLine').value=l.FID;setView('map');selectLine(l.FID);focusLine(l.FID);});}
const v4PreviousScheme=drawScheme;drawScheme=function(){if(currentView==='sld'&&$('v4SldLevel').value==='regional'){v4RegionalSld();return;}v4PreviousScheme();if(currentView==='sld')v4SldInfo();};
function v4RegionalSld(){const s=active?.siteById(selectedSite||$('sldStation').value),svg=$('schemeSvg');svg.replaceChildren();if(!s){putText('schemeTitle','Önce trafo merkezi seçiniz.');return;}const lines=(active.stationLines.get(s.FID)||[]).filter(x=>x.stationA&&x.stationB&&x.stationA!==x.stationB).slice(0,85),sites=new Map([[s.FID,s]]);for(const l of lines){let id=l.stationA===s.FID?l.stationB:l.stationA,neighbor=active.siteById(id);if(neighbor)sites.set(id,neighbor);}const others=[...sites.values()].filter(x=>x.FID!==s.FID).slice(0,36),w=1200,hg=950,cx=w/2,cy=hg/2,pts=new Map([[s.FID,[cx,cy]]]);others.forEach((x,i)=>{let ang=2*Math.PI*i/Math.max(1,others.length)-Math.PI/2;pts.set(x.FID,[cx+440*Math.cos(ang),cy+355*Math.sin(ang)]);});svg.setAttribute('viewBox',`0 0 ${w} ${hg}`);svg.style.width=w*schemeZoom+'px';svg.style.height=hg*schemeZoom+'px';svg.style.maxWidth='none';svg.style.display='block';let ns='http://www.w3.org/2000/svg';function el(tag,attrs,txt){let e=document.createElementNS(ns,tag);for(let [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(txt!==undefined)e.textContent=txt;svg.appendChild(e);return e;}
const display=lines.filter(l=>pts.has(l.stationA)&&pts.has(l.stationB));for(const l of display){const [x1,y1]=pts.get(l.stationA),[x2,y2]=pts.get(l.stationB),key=v4.parallel.get(l.FID),shift=key?(key.index-(key.count-1)/2)*4:0,dx=x2-x1,dy=y2-y1,dist=Math.hypot(dx,dy)||1;let edge=el('line',{x1:x1-dy/dist*shift,y1:y1+dx/dist*shift,x2:x2-dy/dist*shift,y2:y2+dx/dist*shift,stroke:v4VoltStyle(l).color,'stroke-width':Math.min(5,v4VoltStyle(l).width),'stroke-dasharray':v4LineOut(l)?'7 5':'none'});edge.appendChild(document.createElementNS(ns,'title')).textContent=l.FID+' '+l.loc_name+' '+(v4LineOut(l)?'SERVİS DIŞI':'serviste');}
for(const [id,[x,y]] of pts){const site=active.siteById(id);el('circle',{cx:x,cy:y,r:id===s.FID?13:7,fill:id===s.FID?'#f6b968':'#9ae3d6'});el('text',{x:x+11,y:y-9,fill:'#e0f5fa','font-size':'12'},site?.loc_name||id);}putText('schemeTitle',`${s.loc_name}: ${display.length} gerçek DGS hat nesnesi · ${pts.size} TM · indirgenmiş bir-hop şema`);putText('sldInfo','Bölgesel TM–hat grafı DGS gerçek uç referanslarından türetilmiştir; gerçek bara/fider ayrıntıları için TM ve fider görünümünü seçiniz. Paralel devreler ayrı çizilir; servis dışı hat kesiklidir.');}

const v4PreviousSelectLine=selectLine;selectLine=function(id){v4PreviousSelectLine(id);let l=active?.lineById(id);if(!l)return;$('v4ScenarioLine').value=id;$('v4CapacityId').value=id;const cap=v4.capacities.get(id);$('v4Summer').value=cap?.summer||'';$('v4Winter').value=cap?.winter||'';const loading=v4Loading(l);let btn=document.createElement('div');btn.className='chips';btn.innerHTML=`<span class="chip">${v4LineOut(l)?'Senaryo/model: SERVİS DIŞI':'Senaryo/model: serviste'}</span><span class="chip">${l.geoStatus==='Model güzergâhı'?'Kaynak DGS güzergâhı':'TM–TM temsili bağlantı (fiziksel güzergâh değildir)'}</span><span class="chip">${loading?('Kullanıcı '+h(loading.season)+' MVA sınırına göre '+fmt(loading.percent)+' % · '+h(loading.source)):'Yüklenme: doğrulanmış kapasite ve/veya sonuç yok'}</span><button class="sm" id="v4LineOff">Senaryoda servis dışı</button><button class="sm" id="v4LineOn">Senaryoda servise al</button><button class="sm" id="v4LineSld">TM şeması</button>`;$('mapDetail').appendChild(btn);$('v4LineOff').onclick=()=>v4Apply(id,1);$('v4LineOn').onclick=()=>v4Apply(id,0);$('v4LineSld').onclick=()=>{selectedSite=l.stationA||l.stationB;setView('sld');};};
$('v4Geometry').onchange=()=>{cfg.v4Geometry=$('v4Geometry').value;drawMap();};$('v4Season').onchange=()=>{drawMap();if(selectedLine)selectLine(selectedLine);};
$('v4SaveThresholds').onclick=()=>{const t=$('v4Thresholds').value.split(/[;, ]+/).map(Number);if(t.length!==4||t.some(x=>!Number.isFinite(x)||x<0)||t.some((x,i)=>i&&x<t[i-1])){$('v4Thresholds').setCustomValidity('Dört artan, negatif olmayan sınır giriniz.');$('v4Thresholds').reportValidity();return;}$('v4Thresholds').setCustomValidity('');v4.thresholds=t;drawMap();};
$('v4SaveCapacity').onclick=()=>{let id=$('v4CapacityId').value.trim(),l=active?.lineById(id),su=Number($('v4Summer').value),wi=Number($('v4Winter').value);if(!l||!Number.isFinite(su)||!Number.isFinite(wi)||su<=0||wi<=0){putText('v4CapacityMessage','Geçerli hat FID ve iki pozitif MVA değeri giriniz.');return;}v4.capacities.set(id,{summer:su,winter:wi,source:'MANUEL KULLANICI PARAMETRESİ'});putText('v4CapacityMessage',`${id}: yaz ${su} MVA; kış ${wi} MVA · yalnız bu model oturumu, resmî işletme limiti değildir.`);drawMap();};
function v4Apply(id,off){let l=active?.lineById(id);if(!l){v4Notify('Geçerli hat bulunamadı.',true);return;}v4.overrides.set(l.FID,off);v4.activeOverrides=v4.overrides;if(v4.base===null&&v2.sets.length&&!v4.scenario)v4.base=v2.sets[0];v4.scenario=null;v4.scenarioSolver=null;v2.sets.splice(0);v2.selectedSet='';v3.solver=null;stopFlow();listSets();drawMap();v4OverlayStatus();v4Notify(`${l.FID}: ${off?'servis dışı':'serviste'} senaryosuna alındı. Önceki P/Q/V sonucu temizlendi; "Senaryoyu hesapla" düğmesine basın. Orijinal DGS değişmedi.`);}
$('v4ScenarioOff').onclick=()=>{const l=v4ScenarioLine();l?v4Apply(l.FID,1):v4Notify('Hat ID veya adını giriniz.',true);};$('v4ScenarioOn').onclick=()=>{const l=v4ScenarioLine();l?v4Apply(l.FID,0):v4Notify('Hat ID veya adını giriniz.',true);};
$('v4ScenarioRun').onclick=async()=>{if(!active)return v4Notify('Önce bir JSON yükleyiniz.',true);if(!v4.overrides.size)return v4Notify('Senaryo için önce bir hattın durumunu değiştiriniz.',true);if(v3.running)return v4Notify('Başka bir hesap sürüyor.',true);const model=active,stamp=++v4.generation;v4Notify('Senaryo topolojisi kuruluyor, deneysel 66 kV+ AC-PQ hesaplanıyor…');try{await startV3Solver();if(active!==model||stamp!==v4.generation)return;const set=v2.sets[0];if(!set)return v4Notify('Çözüm sonucu yok: raporda yakınsama/ada durumunu inceleyiniz.',true);set.name+=' · SANAL SENARYO';for(const row of set.rows)row.source+=' · SANAL SENARYO';v4.scenario=set;v4.scenarioSolver=v3.solver;v4ValidateCalc();v4Notify(`Senaryo hesabı bitti. ${v3.solver?.solved||0}/${v3.solver?.total||0} ada yakınsadı. Sonuçlar DENEYSEL ve referans doğrulaması yapılmadı.`);v4ScenarioComparison();drawMap();}catch(e){v4Notify('Senaryo hesaplanamadı: '+e.message,true);}};
function v4ScenarioComparison(){const box=$('v4ScenarioTable');if(!v4.scenario){box.innerHTML='';return;}const base=v4.base;const found=v4.scenario.rows.filter(x=>x.cls==='ElmLne'&&x.metric==='P'&&x.terminal==='from'&&x.usable).slice(0,200);let bm=new Map((base?.rows||[]).filter(x=>x.cls==='ElmLne'&&x.metric==='P'&&x.terminal==='from').map(x=>[x.id,x.value]));box.innerHTML=`<p class="mini">İlk 200 hat · ${base?'Referans hesap ve senaryo (her ikisi de deneysel)':'Referans hesap önceden kaydedilmedi; fark hesabı yapılamaz.'}</p><table><thead><tr><th>Hat FID</th><th>Referans MW</th><th>Senaryo MW</th><th>Δ MW</th></tr></thead><tbody>${found.map(r=>{let v=bm.get(r.id),diff=Number.isFinite(v)?r.value-v:null;return `<tr><td>${h(r.id)}</td><td>${v==null?'—':fmt(v)}</td><td>${fmt(r.value)}</td><td>${diff==null?'—':fmt(diff)}</td></tr>`;}).join('')}</tbody></table>`;}
$('v4ScenarioReset').onclick=()=>{if(v3.running)return v4Notify('Önce mevcut hesabın bitmesini bekleyiniz.',true);v4.overrides.clear();v4.activeOverrides=null;v4.scenario=null;if(v4.base){v2.sets.splice(0,v2.sets.length,v4.base);v2.selectedSet=v4.base.id;v3.solver=v4.baseSolver;}else{v2.sets.splice(0);v2.selectedSet='';v3.solver=null;}listSets();v4ScenarioComparison();v4OverlayStatus();v4ValidateCalc();drawMap();};
const v4OldReset=resetV3;resetV3=function(m){v4.generation++;v4.overrides.clear();v4.activeOverrides=null;v4.base=null;v4.baseSolver=null;v4.scenario=null;v4.scenarioSolver=null;v4.capacities.clear();v4.validation=null;v4OldReset(m);v4RenderStyles();v4PopulateStations();v4ComputeParallel();v4OverlayStatus();v4ValidateCalc();};
const v4OldSolver=startV3Solver;startV3Solver=async function(){if(!v4.overrides.size){v4.activeOverrides=null;}const wasBaseline=!v4.overrides.size&&!v42.switchOverrides.size;const out=await v4OldSolver();if(wasBaseline&&v2.sets.length){v4.base=v2.sets[0];v4.baseSolver=v3.solver;}v4ValidateCalc();return out;};
const v4OldNote=updateMapNote;updateMapNote=function(){v4OldNote();if(!active)return;if($('mapMetric').value==='loading'){const got=active.lines.filter(l=>v4Loading(l)).length;putText('mapDataNote',`Yüklenme: ${got} hat; DGS nominal akım veya doğrulanmış Excel/kullanıcı MVA kapasitesi. P/Q sonucu deneysel ise yüzde de deneysel. Uç akımı veya sınır yoksa yüzde gösterilmez.`);}else if(v4.overrides.size&&v4.scenario)putText('mapDataNote','SANAL SENARYO · 66 kV+ deneysel hesap, gerçek SCADA ölçümü veya doğrulanmış N-1 sonucu değildir.');};
$('networkCanvas').addEventListener('pointerup',e=>{if(!active||cfg.v4Geometry!=='simple'||mapCam.dragged||!mapCam.dragging)return;const rect=$('networkCanvas').getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const area=$('mapArea').value,volts=selectedVolts();if($('toggleSites').checked){for(const site of active.sites){if(!visibleSite(site))continue;let p=coordsToPx(site.lon,site.lat);if(Math.hypot(p[0]-x,p[1]-y)<12)return;}}
 let selected=null,best=9;for(const l of active.lines){if(!visibleLine(l,volts,area))continue;if(!l.siteA||!l.siteB||l.siteA.lat==null||l.siteB.lat==null)continue;let [[ax,ay],[bx,by]]=v4LinePixels(l,[[l.siteA.lat,l.siteA.lon],[l.siteB.lat,l.siteB.lon]]),dx=bx-ax,dy=by-ay,den=dx*dx+dy*dy;if(den<.01)continue;let t=Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/den)),d=Math.hypot(x-ax-t*dx,y-ay-t*dy);if(d<best){best=d;selected=l;}}
 if(selected){mapCam.dragging=false;selectLine(selected.FID);e.stopImmediatePropagation();}},true);
$('v4HoverZoom').onchange=()=>{if(!$('v4HoverZoom').checked){const el=$('v4Tip');if(el)el.remove();}};
const v4Net=$('networkCanvas');v4Net.addEventListener('pointermove',e=>{if(true)return; /* v5.3: replaced by spatially indexed TM+line tooltip */clearTimeout(v4.hoverTimer);let x=e.clientX,y=e.clientY;v4.hoverTimer=setTimeout(()=>{const rect=v4Net.getBoundingClientRect(),px=x-rect.left,py=y-rect.top,volts=selectedVolts(),area=$('mapArea').value;let hit=null,best=10;
for(let l of active.lines){if(!visibleLine(l,volts,area))continue;let pts=(cfg.v4Geometry==='simple'?null:l.coords)||[l.siteA?.lat!=null?[l.siteA.lat,l.siteA.lon]:null,l.siteB?.lat!=null?[l.siteB.lat,l.siteB.lon]:null].filter(Boolean);if(pts.length<2)continue;let skip=mapCam.zoom<1.5?Math.max(1,Math.floor(pts.length/35)):1;for(let i=skip;i<pts.length;i+=skip){let pair=v4LinePixels(l,[pts[i-skip],pts[i]]),[ax,ay]=pair[0],[bx,by]=pair[1];if(Math.max(ax,bx)<px-10||Math.min(ax,bx)>px+10||Math.max(ay,by)<py-10||Math.min(ay,by)>py+10)continue;let vx=bx-ax,vy=by-ay,den=vx*vx+vy*vy,t=den?Math.max(0,Math.min(1,((px-ax)*vx+(py-ay)*vy)/den)):0,dist=Math.hypot(px-ax-t*vx,py-ay-t*vy);if(dist<best){hit=l;best=dist;}}}
let tip=$('v4Tip');if(!hit){if(tip)tip.style.display='none';return;}if(!tip){tip=document.createElement('div');tip.id='v4Tip';tip.className='panel';Object.assign(tip.style,{position:'absolute',zIndex:'7',maxWidth:'290px',padding:'9px',pointerEvents:'auto',boxShadow:'0 5px 24px #000a'});$('mapWrap').appendChild(tip);}let load=v4Loading(hit),p=latestResult('ElmLne',hit.FID,'P','from');tip.innerHTML=`<b>${h(hit.FID)} · ${h(hit.loc_name)}</b><br>${h(hit.voltage)} kV · ${v4LineOut(hit)?'SERVİS DIŞI':'serviste'}<br>${hit.geoStatus==='Model güzergâhı'?'Gerçek güzergâh':'TM–TM temsili çizim'}<br>P: ${p?fmt(p.value)+' MW (deneysel/ölçüm kaynağına bakınız)':'Veri yok'}<br>Yüklenme: ${load?fmt(load.percent)+' % (manuel limit)':'Veri yok'}<br><button class="sm" id="v4TipFocus">Hatta odaklan</button>`;tip.style.left=Math.min(rect.width-300,Math.max(4,px+12))+'px';tip.style.top=Math.min(rect.height-150,Math.max(4,py+12))+'px';tip.style.display='block';$('v4TipFocus').onclick=()=>{selectLine(hit.FID);focusLine(hit.FID);};},160);});
for(const [term,name,desc] of [ ['Sade harita','TM–TM kuş uçumu','Elektriksel hat kimliğini ve TM koordinatını koruyan, ancak fiziksel güzergâhı göstermeyen çizim.'],['Servis senaryosu','Yerel hat durumu değişimi','DGS modeli değişmeden, hatların hesap grafından çıkarılabildiği sanal analiz; fiziksel anahtarlama komutu göndermez.'],['Yaz/kış kapasitesi','Kullanıcı işletme sınırı','Bu sürümde hat bazında girilen MVA parametresidir; TEİAŞ resmî mevsimsel sınırı olduğu iddia edilmez.'],['Referans doğrulama','Bağımsız hata testi','Yakınsama bir sayısal denetimdir; gerçek PowerFactory referansına uygunluk ayrıca sınanmalıdır.'] ])GLOSSARY.push([term,name,desc]);
INFO.help+=`<h4>v4.1 kullanım</h4><p>Tek Hat Şeması sekmesinde TM seçerek özet ve fider grafını açın. Haritada Ayrıntılı/Sade görünüm değiştirin. Ayarlardan hat gerilim rengi/kalınlığı ve kullanıcı yaz/kış MVA kapasitesi girin. Analizler sekmesinde sanal hat servis senaryosu hesaplayın. 12:00 referans testindeki hata büyüklükleri giderilmeden P/Q/V ve senaryo sonuçlarını işletme kararı olarak kullanmayın.</p>`;
INFO.map+=`<p>v4.1: Servis dışı hat kesikli, servisli hat düz çizilir; temsili geometrinin kaynağı bilgi panelinde belirtilir. Sade harita TM–TM çizimidir. Tek Hat Şeması ayrı sekmededir, kaynak DGS'ye ait olmayan özgün çizim yerleşimi üretilmez.</p>`;
window.YTBS_V4_TEST={state:()=>({view:currentView,model:active?.name,lines:active?.lines.length,sites:active?.sites.length,geometry:cfg.v4Geometry,selectedLine,scenario:[...v4.overrides],validation:v4.validation,sldNodes:$('schemeSvg').childElementCount,solver:v3.solver,sourceRows:resultSet()?.rows.length||0}),line:id=>active?.lineById(id),setScenario:v4Apply,loading:id=>v4Loading(active.lineById(id)),style:id=>v4VoltStyle(active.lineById(id)),go:setView};
