
'use strict';
/* v4.2 UI/SLD extension. Original DGS parsing, graph and experimental solver retained. */
const v42={kind:'line',filter:'',sort:'name',page:0,opened:false,scope:'filters',bayIndex:null,model:null,hover:null,layout:'horizontal',switchOverrides:new Map(),localComponents:null};
function v42Init(){
 const map=$('view-map'),heading=map.querySelector('.heading');
 const toolbar=document.createElement('div');toolbar.id='v42Toolbar';toolbar.className='v42Toolbar';toolbar.innerHTML=`<div class="v42Row"><span class="v42Caption">HARİTA</span><button id="v42Detailed" class="v42Quick active">Ayrıntılı</button><button id="v42Simple" class="v42Quick">Sade</button><span class="v42Divider"></span><button class="v42Quick active" data-v42metric="inventory">Şebeke</button><button class="v42Quick" data-v42metric="P">P · MW</button><button class="v42Quick" data-v42metric="Q">Q · MVAr</button><button class="v42Quick" data-v42metric="V">V · kV</button><button class="v42Quick" data-v42metric="loading">Yüklenme</button><span class="v42Spacer"></span><button id="v42ToggleFilters" class="v42Quick" aria-controls="v42MapAside" aria-expanded="false">☷ Filtreler</button><button id="v42MapFullscreen" class="v42Quick">⛶ Tam ekran</button></div><div class="v42Row v42VoltageRow"><span class="v42Caption">GERİLİM</span><div id="v42VoltageQuick"></div><span class="v42Spacer"></span><label class="v42Small"><input id="v42Flow" type="checkbox"> Akış okları</label><label class="v42Small"><input id="v42Names" type="checkbox"> TM adları</label><span id="v42TopStatus" class="v42Status">Model bekleniyor</span></div>`;
 heading.after(toolbar);
 document.querySelector('header.apphead h1').textContent='PowerFactory Şebeke Görüntüleyici ve Analiz Sistemi v4.2';
 const scenario=$('v4ScenarioLine')?.closest('.panel');if(scenario){scenario.id='v42ScenarioPanel';$('view-analysis').appendChild(scenario);}
 if($('v4ValidationAnalysis'))$('view-analysis').appendChild($('v4ValidationAnalysis'));
 toolbar.querySelector('.v42Row').insertAdjacentHTML('beforeend','<button id="v42ScenarioShortcut" class="v42Quick">⇄ Hat senaryosu</button>');
 $('v42ScenarioShortcut').onclick=()=>{setView('analysis');$('v42ScenarioPanel')?.scrollIntoView({behavior:'smooth',block:'center'});};
 const initial=map.querySelector('.heading + .panel');if(initial)initial.classList.add('v42Secondary');
 $('resultMapBar').classList.add('v42Secondary');
 const origVolts=$('voltageLayers');$('v42VoltageQuick').appendChild(origVolts); // identical checkbox IDs and visibility source
 const aside=$('v42MapAside');
 $('v42ToggleFilters').onclick=()=>{const show=aside.classList.toggle('v42Open');$('v42ToggleFilters').setAttribute('aria-expanded',String(show));requestAnimationFrame(()=>{resizeMap();drawMap();});};
 $('v42Detailed').onclick=()=>{$('v4Geometry').value='detailed';$('v4Geometry').dispatchEvent(new Event('change'));v42SyncToolbar();};
 $('v42Simple').onclick=()=>{$('v4Geometry').value='simple';$('v4Geometry').dispatchEvent(new Event('change'));v42SyncToolbar();};
 $$('[data-v42metric]',toolbar).forEach(b=>b.onclick=()=>{$('mapMetric').value=b.dataset.v42metric;$('mapMetric').dispatchEvent(new Event('change'));v42SyncToolbar();v42RenderLightning();});
 $('v42Flow').onchange=e=>{$('mapFlow').checked=e.target.checked;$('mapFlow').dispatchEvent(new Event('change'));};
 $('v42Names').onchange=e=>{$('toggleNames').checked=e.target.checked;$('toggleNames').dispatchEvent(new Event('change'));};
 $('v42MapFullscreen').onclick=()=>{const root=$('view-map');if(document.fullscreenElement)document.exitFullscreen?.();else root.requestFullscreen?.().catch(()=>{});};
 const wrap=$('mapWrap');const zap=document.createElement('button');zap.id='v42LightningButton';zap.type='button';zap.textContent='⚡';zap.setAttribute('aria-label','Elektriksel veriler panelini aç');zap.setAttribute('aria-expanded','false');wrap.appendChild(zap);
 const pane=document.createElement('section');pane.id='v42LightningPanel';pane.className='v42LightningPanel hidden';pane.setAttribute('aria-label','Elektriksel veriler');pane.innerHTML=`<header><strong>⚡ Elektriksel Veriler</strong><button id="v42LightningClose" aria-label="Paneli kapat">✕</button></header><div class="v42Ltabs"><button data-v42kind="line" class="active">Hatlar</button><button data-v42kind="trafo">Trafolar</button><button data-v42kind="bus">Baralar</button></div><div class="v42Controls"><label>Gösterilen değer<select id="v42Metric"><option value="P">Aktif güç · MW</option><option value="Q">Reaktif güç · MVAr</option><option value="V">Gerilim · kV</option><option value="loading">Yüklenme · %</option></select></label><label>Sıralama<select id="v42Sort"><option value="name">Ekipman adı</option><option value="abs">Değer büyüklüğü</option><option value="id">Ekipman kimliği</option></select></label><label class="v42Small"><input id="v42VisibleOnly" type="checkbox"> Yalnız haritada görünür alan</label><input id="v42Search" type="search" placeholder="Ekipman adı veya kimliği…" aria-label="Elektriksel veri listesinde ara"></div><div id="v42LNote" class="v42LNote">Önce DGS JSON yükleyiniz.</div><div class="v42LScroll"><table><thead><tr><th>Ekipman</th><th>Değer</th><th>Kaynak</th></tr></thead><tbody id="v42LBody"></tbody></table><div id="v42LPager"></div></div>`;wrap.appendChild(pane);
 zap.onclick=()=>{v42.opened=!v42.opened;v42UpdatePanel();};$('v42LightningClose').onclick=()=>{v42.opened=false;v42UpdatePanel();};
 $$('[data-v42kind]',pane).forEach(b=>b.onclick=()=>{v42.kind=b.dataset.v42kind;v42.page=0;v42SyncLightningTabs();v42RenderLightning();});
 for(const id of ['v42Metric','v42Sort','v42Search','v42VisibleOnly'])$(id).addEventListener(id==='v42Search'?'input':'change',()=>{v42.page=0;v42RenderLightning();});
 if(window.ResizeObserver)new ResizeObserver(()=>{if(currentView==='map'&&mapMode==='geo'){resizeMap();drawMap();}}).observe(wrap);
 const level=$('v4SldLevel');level.innerHTML='<option value="node">Node-Breaker · Gerçek anahtar bağlantıları</option><option value="station">TM özet · Bara/fider</option><option value="regional">Bölgesel · TM–hat</option>';
 const switchStatus=document.createElement('div');switchStatus.id='v42SwitchAnalysis';switchStatus.className='notice warn';switchStatus.textContent='Sanal anahtar senaryosu bulunmuyor.';$('analysisKinds')?.parentElement?.before(switchStatus);const block=document.createElement('div');block.id='v42SldBar';block.className='v42SldBar';block.innerHTML=`<label>Fider (ayrıntılı bağlantı)<select id="v42Bay" aria-label="SLD için fider seç"><option value="">Önce TM seçiniz</option></select></label><label>Şema yerleşimi<select id="v42SldLayout"><option value="horizontal">Yatay elektriksel akış</option><option value="vertical">Dikey elektriksel akış</option></select></label><span class="v42SldBadge" id="v42SldBadge">DGS referanslarından otomatik çizim; PowerFactory özgün sayfa düzeni değildir.</span><button class="sm" id="v42SldFit">Ekrana sığdır</button>`;
 $('sldHost').before(block);
 $('v42Bay').onchange=()=>{selectedFider=$('v42Bay').value||null;drawScheme();};
 $('v42SldLayout').onchange=e=>{v42.layout=e.target.value;drawScheme();};
 $('v42SldFit').onclick=()=>{schemeZoom=1;drawScheme();};
 $('v4SldLevel').value='node';
 $('view-info').querySelector('.heading h2').textContent='Bilgi ve Teknik Sözlük · DGS / SLD / Harita / Analizler';
 v42SyncToolbar();v42UpdatePanel();
}
function v42SyncToolbar(){ $('v42Detailed').classList.toggle('active',cfg.v4Geometry!=='simple');$('v42Simple').classList.toggle('active',cfg.v4Geometry==='simple');$$('[data-v42metric]').forEach(b=>b.classList.toggle('active',b.dataset.v42metric===$('mapMetric').value));$('v42Flow').checked=$('mapFlow').checked;$('v42Names').checked=$('toggleNames').checked;}
function v42BuildVolts(){const box=$('voltageLayers');if(!active)return;const prev=[...box.querySelectorAll('[data-volt]')].map(e=>[e.dataset.volt,e.checked]);let allowed=new Map(prev);const termTable=active.t('ElmTerm'),uix=active.attrAt('ElmTerm','uknom');const voltageData=[...active.lines.map(l=>Number.isFinite(l.voltage)?String(l.voltage):'other'),...(termTable?.Values||[]).map(r=>{let u=Number(r[uix]);return Number.isFinite(u)&&u>0?String(u):'other';})];const list=[...new Set(voltageData)].sort((a,b)=>Number(b)-Number(a));const major=list.filter(v=>v!=='other'&&Number(v)>33);const minor=list.filter(v=>v!=='other'&&Number(v)<=33);function item(v){const c=v4.styles.get(v)?.color||VOLT_COLORS[v]||VOLT_COLORS.other;return `<label class="v42Volt"><input type="checkbox" data-volt="${h(v)}" ${allowed.get(v)!==false?'checked':''}><span style="background:${h(c)}"></span>${h(v)} kV</label>`;}
 box.innerHTML=major.map(item).join('')+(minor.length?`<details class="v42Minor"><summary>≤33 kV (${minor.length})</summary><div class="v42MinorBody">${minor.map(item).join('')}</div></details>`:'')+(list.includes('other')?item('other'):'');
 $$('[data-volt]',box).forEach(e=>e.onchange=()=>{drawMap();v42RenderLightning();});
 $('v42TopStatus').textContent=`${nf.format(active.lines.length)} hat · ${nf.format(active.sites.length)} TM · ${active.date} ${active.time}`;
}
function v42UpdatePanel(){const p=$('v42LightningPanel');p.classList.toggle('hidden',!v42.opened);$('v42LightningButton').setAttribute('aria-expanded',String(v42.opened));if(v42.opened)v42RenderLightning();}
function v42SyncLightningTabs(){$$('[data-v42kind]',$('v42LightningPanel')).forEach(b=>b.classList.toggle('active',b.dataset.v42kind===v42.kind));}
function v42Result(cls,id,metric,terminal=null){if(v42.switchOverrides.size&&SC.viewMode!=='reference'&&(!v4.scenario||SC.pending))return null;return latestResult(cls,id,metric,terminal);}
function v42Value(cls,id,metric){if(v42.switchOverrides.size&&SC.viewMode!=='reference'&&(!v4.scenario||SC.pending))return null;if(metric==='loading'&&cls==='ElmLne'){let a=v4Loading(active.lineById(id));return a?{value:a.percent,unit:'%',source:a.source||'MANUEL KAPASİTE',quality:'CALCULATED'}:null;}
 if(metric==='loading'&&cls!=='ElmLne')return null;
 return v42Result(cls,id,metric);}
function v42Source(r){if(!r)return 'Veri yok';const s=String(r.source||'').toUpperCase();return s.includes('MEAS')||s.includes('ÖLÇÜM')?'Ölçüm':s.includes('MANUEL')?'Parametre':'Deneysel hesap';}
function v42List(){if(!active)return [];
 const selected=selectedVolts(),area=$('mapArea').value,visibleOnly=$('v42VisibleOnly').checked,needle=norm($('v42Search').value.trim()),metric=$('v42Metric').value,items=[];
 const add=(cls,id,name,voltage,station,kind,extra)=>{const label=`${id} ${name}`;if(needle&&!norm(label).includes(needle))return;let v=v42Value(cls,id,metric);items.push({cls,id,name,voltage,station,kind,value:v,extra});};
 if(v42.kind==='line'){for(const l of active.lines){if(!visibleLine(l,selected,area))continue;if(visibleOnly){const p=l.siteA?.lat!=null?coordsToPx(l.siteA.lon,l.siteA.lat):null;const q=l.siteB?.lat!=null?coordsToPx(l.siteB.lon,l.siteB.lat):null;if(p&&q&&(p[0]<0&&q[0]<0||p[0]>mapCam.w&&q[0]>mapCam.w||p[1]<0&&q[1]<0||p[1]>mapCam.h&&q[1]>mapCam.h))continue;}add('ElmLne',l.FID,l.loc_name,l.voltage,l.stationA,'line',l);}}
 else if(v42.kind==='trafo'){const t=active.t('ElmTr2');for(let i=0;i<(t?.Values.length||0);i++){let r=active.row('ElmTr2',i);const sid=active.resolveSiteByClass('ElmTr2',r.FID);const site=active.siteById(sid);if(area&&site?.ytmId!==area)continue;if(visibleOnly&&site?.lat!=null){let [x,y]=coordsToPx(site.lon,site.lat);if(x<0||x>mapCam.w||y<0||y>mapCam.h)continue;}const typ=active.get('TypTr2',r.typ_id);const hvCube=active.get('StaCubic',r.bushv||r.bus1);const hvTerm=active.get('ElmTerm',hvCube?.fold_id);let u=Number(hvTerm?.uknom||typ?.utrn_h);if(Number.isFinite(u)&&!selected.has(String(u)))continue;add('ElmTr2',r.FID,r.loc_name,u,sid,'trafo',r);}}
 else {const t=active.t('ElmTerm');const ix=active.attrAt('ElmTerm','uknom');for(let i=0;i<(t?.Values.length||0);i++){let row=t.Values[i],u=Number(row[ix]);if(!selected.has(String(u)))continue;let fid=row[active.attrAt('ElmTerm','FID')];let sid=active.resolveSiteByClass('ElmTerm',fid);const site=active.siteById(sid);if(area&&site?.ytmId!==area)continue;if(visibleOnly){if(site?.lat==null)continue;let [x,y]=coordsToPx(site.lon,site.lat);if(x<0||x>mapCam.w||y<0||y>mapCam.h)continue;}let name=row[active.attrAt('ElmTerm','loc_name')]||fid;add('ElmTerm',fid,String(name),u,sid,'bus',null);}}
 const sort=$('v42Sort').value;if(sort==='abs')items.sort((a,b)=>(Number.isFinite(b.value?.value)?Math.abs(b.value.value):-Infinity)-(Number.isFinite(a.value?.value)?Math.abs(a.value.value):-Infinity));else items.sort((a,b)=>sort==='id'?a.id.localeCompare(b.id,'tr'):a.name.localeCompare(b.name,'tr'));
 return items;
}
function v42RenderLightning(){if(!v42.opened)return;const tbody=$('v42LBody'),note=$('v42LNote');if(!active){tbody.innerHTML='';note.textContent='Önce YTBS DGS JSON dosyasını yükleyiniz.';return;}const items=v42List(),per=70,totalPages=Math.max(1,Math.ceil(items.length/per));v42.page=Math.min(v42.page,totalPages-1);let subset=items.slice(v42.page*per,(v42.page+1)*per),metric=$('v42Metric').value;
 note.textContent=`${nf.format(items.length)} kayıt · ${active.date} ${active.time} · Harita/YTM/gerilim filtreleri uygulanır · Ölçüm ve deneysel hesap ayrıdır.`;
 tbody.innerHTML=subset.map(x=>{const v=x.value;const label=v&&Number.isFinite(v.value)?fmt(v.value)+' '+h(v.unit||unitMap[metric]||''):'Veri yok';return `<tr data-v42item="${h(x.cls+'|'+x.id)}" class="${x.id===(selectedLine||selectedSite)?'v42Selected':''}"><td><b>${h(x.id)}</b><br><small>${h(x.name.slice(0,52))}</small><br><small>${Number.isFinite(x.voltage)?h(x.voltage)+' kV':''}</small></td><td>${label}</td><td><small>${v42Source(v)}</small></td></tr>`;}).join('')||'<tr><td colspan="3">Bu filtrede ekipman yok.</td></tr>';
 $$('#v42LBody tr[data-v42item]').forEach(row=>row.onclick=()=>{let [cls,id]=row.dataset.v42item.split('|');if(cls==='ElmLne'){selectLine(id);focusLine(id);}else if(cls==='ElmTerm'){let sid=active.resolveSiteByClass('ElmTerm',id);if(sid){selectSite(sid);focusSite(sid);}}else {let sid=active.resolveSiteByClass(cls,id);if(sid){selectSite(sid);focusSite(sid);}}v42RenderLightning();});
 $('v42LPager').innerHTML=`<button class="sm" id="v42Prev" ${v42.page===0?'disabled':''}>◀</button> ${v42.page+1}/${totalPages} <button class="sm" id="v42Next" ${v42.page>=totalPages-1?'disabled':''}>▶</button>`;$('v42Prev').onclick=()=>{v42.page--;v42RenderLightning();};$('v42Next').onclick=()=>{v42.page++;v42RenderLightning();};
}
function v42EnsureSldIndexes(){if(!active)return; if(v42.model===active&&v42.bayIndex)return;v42.model=active;v42.bayIndex=new Map();v42.cubesByTerm=new Map();const c=active.t('StaCubic'),cf=active.attrAt('StaCubic','fold_id'),co=active.attrAt('StaCubic','obj_id');for(const row of c?.Values||[]){const tid=row[cf],obj=String(row[co]||'');if(!tid||!obj||obj.startsWith('C'))continue;let list=v42.cubesByTerm.get(tid);if(!list)v42.cubesByTerm.set(tid,list=[]);if(!list.includes(obj))list.push(obj); }const t=active.t('ElmTerm');let f=active.attrAt('ElmTerm','fold_id'),id=active.attrAt('ElmTerm','FID');for(const row of t?.Values||[]){let bay=row[f];if(!bay)continue;let ls=v42.bayIndex.get(bay);if(!ls)v42.bayIndex.set(bay,ls=[]);ls.push(row[id]);}}
function v42SwitchKind(sw){const kind=String(sw.aUsage||'').toLowerCase();if(kind==='cbk')return {name:'Kesici',code:'cbk'};if(kind==='dct')return {name:'Ayırıcı',code:'dct'};return {name:kind==='sdc'?'Diğer anahtarlama (sdc)':'Türü doğrulanmamış anahtar',code:'generic'};}
function v42StationBayList(){if(!active)return;const site=active.siteById(selectedSite||$('sldStation').value),el=$('v42Bay');if(!site)return;let bays=active.getEquipmentForSite(site.FID,'ElmBay');let old=el.value;el.innerHTML='<option value="">Fider seçiniz</option>'+bays.map(b=>`<option value="${h(b.FID)}">${h(b.FID)} · ${h(b.loc_name)}</option>`).join('');el.value=bays.some(b=>b.FID===old)?old:'';if(!$('v42Bay').value&&bays.length)$('v42Bay').value=bays[0].FID;}
function v42NodeSld(){const site=active?.siteById(selectedSite||$('sldStation').value),svg=$('schemeSvg');svg.replaceChildren();if(!site){$('schemeTitle').textContent='Önce trafo merkezi seçin.';return;}v42EnsureSldIndexes();const bays=active.getEquipmentForSite(site.FID,'ElmBay');if(!bays.length){$('v42SldBadge').textContent='Bu modelde fider sınıfı yok: indirgenmiş SLD gösteriliyor.';v4PreviousScheme();return;}let bid=$('v42Bay').value;if(!bays.some(b=>b.FID===bid)){v42StationBayList();bid=$('v42Bay').value;}const bay=active.get('ElmBay',bid);if(!bay)return;
 selectedFider=bid;const termIds=v42.bayIndex.get(bid)||[],switches=active.getEquipmentForSite(site.FID,'ElmCoup').filter(sw=>sw.fold_id===bid),nodes=new Map(),edges=[];
 for(const tid of termIds){const n=active.get('ElmTerm',tid);if(n)nodes.set(tid,n);}for(const sw of switches){const a=active.get('StaCubic',sw.bus1)?.fold_id||null,b=active.get('StaCubic',sw.bus2)?.fold_id||null;for(const tid of [a,b])if(tid&&!nodes.has(tid)){const n=active.get('ElmTerm',tid);if(n)nodes.set(tid,n);}edges.push({sw,a,b});}
 const external=[...nodes.values()].filter(n=>n.fold_id!==bid).map(n=>n.FID),adj=new Map([...nodes.keys()].map(id=>[id,[]]));for(const e of edges)if(adj.has(e.a)&&adj.has(e.b)){adj.get(e.a).push(e.b);adj.get(e.b).push(e.a);}v42.localComponents={before:v42BayComponents(nodes,edges,false),scenario:v42BayComponents(nodes,edges,true),site:site.FID,bay:bid};let level=new Map(),q=external.length?external:[...nodes.keys()].slice(0,1);for(const id of q)level.set(id,0);for(let j=0;j<q.length;j++){let id=q[j];for(const n of adj.get(id)||[])if(!level.has(n)){level.set(n,level.get(id)+1);q.push(n);}}for(const id of nodes.keys())if(!level.has(id))level.set(id,Math.max(1,...level.values())+1);
 const bands=new Map();for(const [id,lv] of level){let list=bands.get(lv);if(!list)bands.set(lv,list=[]);list.push(id);}const maxCol=Math.max(0,...bands.keys()),maxRows=Math.max(1,...[...bands.values()].map(v=>v.length)),horizontal=v42.layout==='horizontal',w=horizontal?Math.max(1120,300+maxCol*250):Math.max(1100,250+maxRows*185),hh=horizontal?Math.max(650,270+maxRows*135):Math.max(700,250+maxCol*220);svg.setAttribute('viewBox',`0 0 ${w} ${hh}`);svg.style.width=w*schemeZoom+'px';svg.style.height=hh*schemeZoom+'px';svg.style.maxWidth='none';svg.style.display='block';svg.setAttribute('role','img');svg.setAttribute('aria-label','DGS terminal referanslarından oluşturulan ayrıntılı anahtarlama şeması');
 const NS='http://www.w3.org/2000/svg';const g=(tag,at={},parent=svg)=>{let e=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(at))e.setAttribute(k,String(v));parent.appendChild(e);return e;};const txt=(x,y,t,size=12,clr='#d8ecf2')=>{const e=g('text',{x,y,fill:clr,'font-size':size,'font-family':'system-ui'});e.textContent=String(t);return e;};
 txt(24,32,`${site.loc_name} · ${bay.loc_name} · ${bay.FID}`,19,'#fff0cb');txt(24,55,`${nodes.size} gerçek terminal · ${edges.length} anahtar · bağlantı: StaCubic → ElmTerm`,12);
 const pos=new Map();for(const [lv,list] of bands){list.sort((a,b)=>a.localeCompare(b,'tr'));list.forEach((id,i)=>pos.set(id,horizontal?[120+lv*250,140+i*135]:[140+i*185,130+lv*220]));}
 const pairNum=new Map();for(const {sw,a,b} of edges){if(!pos.has(a)||!pos.has(b))continue;const key=[a,b].sort().join('|'),ix=pairNum.get(key)||0;pairNum.set(key,ix+1);let [ax,ay]=pos.get(a),[bx,by]=pos.get(b);let dx=bx-ax,dy=by-ay,dist=Math.hypot(dx,dy)||1,px=-dy/dist*ix*12,py=dx/dist*ix*12;ax+=px;ay+=py;bx+=px;by+=py;const mx=(ax+bx)/2,my=(ay+by)/2,k=v42SwitchKind(sw),on=Number(v42.switchOverrides.has(sw.FID)?v42.switchOverrides.get(sw.FID):sw.on_off)===1,col=on?'#71e0bf':'#ffc57e';
 g('line',{x1:ax,y1:ay,x2:mx-dx/dist*18,y2:my-dy/dist*18,stroke:'#75a7bf','stroke-width':2});g('line',{x1:mx+dx/dist*18,y1:my+dy/dist*18,x2:bx,y2:by,stroke:'#75a7bf','stroke-width':2});
 const group=g('g',{'data-switch':sw.FID,role:'button',tabindex:0,'aria-label':k.name+' '+sw.FID+' '+(on?'kapalı':'açık'),style:'cursor:pointer'});group.appendChild(g('rect',{x:mx-22,y:my-22,width:44,height:44,rx:7,fill:'#173247',stroke:col,'stroke-width':1.2},group));
 if(k.code==='cbk'){g('rect',{x:mx-8,y:my-10,width:16,height:20,fill:'none',stroke:col,'stroke-width':2.2},group);g('line',{x1:mx-12,y1:my-13,x2:mx+12,y2:my+13,stroke:col,'stroke-width':on?2.5:0,opacity:on?1:0},group);if(!on)g('line',{x1:mx-11,y1:my-12,x2:mx-3,y2:my-3,stroke:col,'stroke-width':2.5},group);}
 else if(k.code==='dct'){g('circle',{cx:mx-11,cy:my,r:3,fill:col},group);g('circle',{cx:mx+11,cy:my,r:3,fill:col},group);g('line',{x1:mx-11,y1:my,x2:mx+8,y2:on?my:my-12,stroke:col,'stroke-width':2.5},group);}
 else {g('polygon',{points:`${mx},${my-10} ${mx+10},${my} ${mx},${my+10} ${mx-10},${my}`,fill:'none',stroke:col,'stroke-width':2},group);}
 const title=g('title',{},group);title.textContent=`${k.name} ${sw.FID} · ${on?'Kapalı':'Açık'} · ${a} ↔ ${b}`;txt(mx-31,my-30,sw.FID,10,col);
 group.addEventListener('click',()=>v42SwitchInfo(sw,a,b,site,bay));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();v42SwitchInfo(sw,a,b,site,bay);}});
 }
 for(const [id,[x,y]] of pos){const nd=nodes.get(id),outer=nd.fold_id!==bid,group=g('g',{role:'button',tabindex:0,'data-terminal':id,style:'cursor:pointer'});if(outer){g('line',{x1:x-55,y1:y,x2:x+55,y2:y,stroke:'#efbd79','stroke-width':6},group);}else{g('circle',{cx:x,cy:y,r:9,fill:'#7bd5e2',stroke:'#ddf8ff','stroke-width':1.5},group);}const nm=String(nd.loc_name||'').slice(0,25);txt(x-65,y+27,`${id} ${outer?'(dış bara)':''}`,10);txt(x-65,y+41,nm,10,'#a8becd');group.addEventListener('click',()=>openEquipment('ElmTerm',id));}
 // Power-equipment stubs are drawn only where StaCubic explicitly binds the equipment to the selected terminal.
 for(const [tid,[x,y]] of pos){const devices=(v42.cubesByTerm?.get(tid)||[]).filter(fid=>/^[HTULRK]/.test(fid)).slice(0,3);if(!devices.length)continue;
 devices.forEach((fid,i)=>{const types=[['ElmLne','Hat'],['ElmTr2','Trafo'],['ElmSym','Ünite'],['ElmGenStat','Statik ünite'],['ElmLod','Yük'],['ElmShnt','Şönt'],['ElmScap','Seri kapasitör'],['ElmNec','Topraklama trafosu']];const match=types.find(([cl])=>active.get(cl,fid));if(!match)return;const [cls,label]=match;let xx=x+(i-1)*63,yy=y+57;g('line',{x1:x,y1:y+10,x2:xx,y2:yy-9,stroke:'#6494ae','stroke-width':1.2});const elem=g('g',{'data-power':fid,style:'cursor:pointer'});if(cls==='ElmTr2'||cls==='ElmNec'){g('circle',{cx:xx-5,cy:yy,r:7,fill:'none',stroke:'#c9b8e9','stroke-width':2},elem);g('circle',{cx:xx+5,cy:yy,r:7,fill:'none',stroke:'#c9b8e9','stroke-width':2},elem);}else if(cls==='ElmLne'){g('path',{d:`M${xx-10},${yy+7} L${xx},${yy-6} L${xx+10},${yy+7}`,fill:'none',stroke:'#74b7ea','stroke-width':2},elem);}else {g('circle',{cx:xx,cy:yy,r:9,fill:'#24465b',stroke:'#b6d9dd','stroke-width':1.5},elem);const sym=g('text',{x:xx-4,y:yy+4,fill:'#e3f6ef','font-size':10},elem);sym.textContent=cls==='ElmLod'?'Y':'G';}const lab=g('text',{x:xx-32,y:yy+22,fill:'#b2cbd8','font-size':9},elem);lab.textContent=fid;const title=g('title',{},elem);title.textContent=label+' '+fid+' · bağlı terminal '+tid;elem.addEventListener('click',()=>openEquipment(cls,fid));});
 }
 $('schemeTitle').textContent=`${site.loc_name} / ${bay.loc_name} · Node-Breaker · DGS gerçek anahtar uçları`;
 $('v42SldBadge').textContent=`${nodes.size} terminal / ${edges.length} anahtar · Fider bağlı bileşeni ${v42.localComponents.before} → ${v42.localComponents.scenario} · ${edges.filter(e=>!e.a||!e.b).length} çözülemeyen uç · Otomatik graf yerleşimi.`;
 $('mapDetail').innerHTML=`<b>${h(bay.loc_name)}</b> · ${h(bid)} · ${nodes.size} terminal / ${edges.length} anahtarlama elemanı. Açık anahtarlar açıktır; sahada enerjilendirme sonucu değildir.`;
}
function v42BayComponents(nodes,edges,scenario){let adj=new Map([...nodes.keys()].map(id=>[id,[]]));for(const {sw,a,b} of edges){if(!adj.has(a)||!adj.has(b))continue;const on=Number(scenario&&v42.switchOverrides.has(sw.FID)?v42.switchOverrides.get(sw.FID):sw.on_off)===1;if(!on)continue;adj.get(a).push(b);adj.get(b).push(a);}let seen=new Set(),components=0;for(const id of adj.keys()){if(seen.has(id))continue;components++;const q=[id];seen.add(id);for(let i=0;i<q.length;i++)for(const next of adj.get(q[i]))if(!seen.has(next)){seen.add(next);q.push(next);}}return components;}
function v42SwitchInfo(sw,a,b,site,bay){const k=v42SwitchKind(sw),model=Number(sw.on_off)===1,scenario=Number(v42.switchOverrides.has(sw.FID)?v42.switchOverrides.get(sw.FID):sw.on_off)===1;
$('sldInfo').innerHTML=`<div class="sectiontitle">${h(k.name)} · ${h(sw.FID)}</div><p>${h(sw.loc_name||'')} · ${h(site.loc_name)} / ${h(bay.loc_name)}</p><div class="detailgrid"><div class="kv"><small>Model pozisyonu</small><b>${model?'KAPALI':'AÇIK'}</b></div><div class="kv"><small>Senaryo pozisyonu</small><b>${scenario?'KAPALI':'AÇIK'}</b></div><div class="kv"><small>Terminal 1</small><b>${h(a||'Çözülemedi')}</b></div><div class="kv"><small>Terminal 2</small><b>${h(b||'Çözülemedi')}</b></div><div class="kv"><small>DGS anahtar türü</small><b>${h(sw.aUsage||'Bilinmiyor')}</b></div><div class="kv"><small>Yerel fider bileşen sayısı</small><b>${v42.localComponents?.before??'—'} → ${v42.localComponents?.scenario??'—'}</b></div></div><div class="chips"><button class="sm" id="v42SwitchOpen">Senaryoda aç</button><button class="sm" id="v42SwitchClose">Senaryoda kapat</button><button class="sm" id="v42SwitchReset">Model pozisyonuna dön</button><button class="sm" id="v42SwitchRaw">Ham ekipman kaydı</button><button class="sm primary" id="v52SwitchCompute">Senaryoyu hesapla</button></div><p class="mini">Sanal anahtarın topoloji etkisi yerel olarak görülebilir; Senaryoyu hesapla düğmesiyle 66 kV+ deneysel AC çözüm başlatılır. Gerçek saha kumandası veya doğrulanmış işletme güvenliği sonucu değildir. Senaryo aktifken başlangıç modelinin P/Q/V sonuçları senaryo verisi gibi gösterilmez.</p>`;
function change(next){ScenarioController.applySwitch(sw.FID,next);drawScheme();v42SwitchInfo(sw,a,b,site,bay);v42RenderSwitchAnalysis();drawMap();v42RenderLightning();}
$('v42SwitchOpen').onclick=()=>change(false);$('v42SwitchClose').onclick=()=>change(true);$('v42SwitchReset').onclick=()=>change(null);$('v42SwitchRaw').onclick=()=>openEquipment('ElmCoup',sw.FID);$('v52SwitchCompute').onclick=()=>window.ScenarioController.run();}
function v42RenderSwitchAnalysis(){if(!$('v42SwitchAnalysis'))return;$('v42SwitchAnalysis').innerHTML=v42.switchOverrides.size?`<b>Yerel sanal anahtar senaryosu:</b> ${v42.switchOverrides.size} anahtar için geçici pozisyon. Son seçilen fiderde bağlı bileşen sayısı: ${v42.localComponents?.before??'—'} → ${v42.localComponents?.scenario??'—'}. <b>Ülke geneli deneysel yük akışı için 'Senaryoyu hesapla' kullanın.</b> <button class="sm" id="v42ResetSwitchScenario">Anahtar değişikliklerini sıfırla</button>`:'Sanal anahtar senaryosu bulunmuyor. SLD’de bir kesici veya ayırıcıyı seçebilirsiniz.';const button=$('v42ResetSwitchScenario');if(button)button.onclick=()=>{ScenarioController.clearSwitches();v42.localComponents=null;v42RenderSwitchAnalysis();drawScheme();drawMap();v42RenderLightning();};}
/* Make a separate detailed SLD mode, retaining original station summary and regional modes. */
const v42OldDraw=drawScheme;drawScheme=function(){if(currentView==='sld'&&active&&$('v4SldLevel').value==='node'){v42NodeSld();return;}v42OldDraw();};
const v42OldSetView=setView;setView=function(v){v42OldSetView(v);if(v==='map'){v42SyncToolbar();if(v42.opened)v42RenderLightning();}if(v==='sld'&&active){v42StationBayList();if($('v4SldLevel').value==='node')requestAnimationFrame(drawScheme);}};
const v42OldActivate=activateModel;activateModel=function(m){v42.model=null;v42.bayIndex=null;v42.cubesByTerm=null;v42.switchOverrides.clear();v42OldActivate(m);v42RenderSwitchAnalysis();if(m){v42BuildVolts();v42StationBayList();}else{$('v42TopStatus').textContent='Model bekleniyor';$('v42LBody').replaceChildren();}v42RenderLightning();};
const v42OldSelectLine=selectLine;selectLine=function(id){v42OldSelectLine(id);if(v42.opened)v42RenderLightning();};
const v42OldSelectSite=selectSite;selectSite=function(id){v42OldSelectSite(id);if(v42.opened)v42RenderLightning();};
$('v4SldLevel').onchange=()=>{if($('v4SldLevel').value==='node')v42StationBayList();else selectedFider=null;drawScheme();};
$('sldStation').onchange=()=>{let id=$('sldStation').value;if(!id)return;selectSite(id);v42StationBayList();drawScheme();};
/* Keep map color styling when user changes per-voltage color in Settings. */
const v42OldStyle=v4RenderStyles;v4RenderStyles=function(){v42OldStyle();if(active)v42BuildVolts();};
const v42OldLatestResult=latestResult;latestResult=function(...args){if(v42.switchOverrides.size&&SC.viewMode!=='reference'&&(!v4.scenario||SC.pending))return null;return v42OldLatestResult(...args);};
INFO.map+=`<p><b>Güzergâh düz çizgisi:</b> Servisteki temsili TM–TM bağlantısı da düz çizilir; geometrinin temsili olduğu ekipman panelinde yazılır. Kesikli çizgi servis dışı durumu gösterir.</p><h4>v4.2 · Geniş harita ve ⚡ paneli</h4><p>Harita sekmesi altında yatay kontrol çubuğu bulunur. 33 kV ve altı hat gerilimleri ortak bir grup altında açılır. Sağ alttaki ⚡ simgesi ile Hatlar, Trafolar ve Baralar listelenir; kaynak, model saati ve eksik sonuç açıkça belirtilir. Listeden ekipman seçildiğinde haritada konumlanılır. Akış ve gerilim sonuçları gömülü ölçüm veya deneysel hesap kökenlidir. Harita çizgi stili servis durumunu, güzergâh niteliği ise ayrı bilgi alanını ifade eder.</p>`;
INFO.help+=`<p>Sanal kesici/ayırıcı değişiklikleri yerel fider bağlantı bileşen sayısını karşılaştırır. Bu sürümde anahtar senaryosu için ülke geneli yeniden AC çözümü bulunmaz. Başlangıç modelinin değerleri senaryo sonucu değildir.</p><h4>v4.2 · Gelişmiş SLD</h4><p>Tek Hat Şeması sekmesinde <b>Node-Breaker</b> kapsamını seçin, TM ve fider seçin. Gerçek StaCubic–ElmTerm uçlarıyla bulunan anahtarlar kesici / ayırıcı / diğer sembolleriyle ve modeldeki açık-kapalı durumlarıyla SVG üzerinde çizilir. Elektriksel düğüm/topoloji referansları korunur; grafik yerleşimi otomatik olduğu için özgün PowerFactory sayfa düzeninin kopyası değildir. Kesici sembolünü seçerek gerçek kimlik ve terminalleri inceleyin. Sanal anahtar pozisyonu değiştirme henüz uygulanmamıştır.</p>`;
GLOSSARY.push(['Node-Breaker SLD','Anahtarlamalı düğüm grafı','Bara ve terminal nesneleri ile kesici/ayırıcı bağlantıları DGS StaCubic referanslarıyla oluşturulur; semboller otomatik yerleştirilir.'],['Şimşek paneli','⚡ Elektriksel veriler','Hat, trafo ve bara listeleri; seçilen gerilim/YTM katmanına göre filtrelenir. Ölçüm ve hesap sonuçları ayrı kaynakla işaretlenir.'],['cbk','Kesici tür kodu','ElmCoup.aUsage içinde kesici türünü ifade eden kod.'],['dct','Ayırıcı tür kodu','ElmCoup.aUsage içinde ayırıcı türü kodu.'],['sdc','Diğer anahtarlama kodu','Bu modelde kullanılan üçüncü sınıf; kesin cihaz alt türü doğrulanmadan jenerik sembolle gösterilir.'] );
v42Init();
window.YTBS_V42_TEST={state:()=>({view:currentView,model:active?.name,sites:active?.sites.length,lines:active?.lines.length,toolbar:!!$('v42Toolbar'),voltageGroups:$$('[data-volt]').length,minor:!!$('voltageLayers').querySelector('.v42Minor'),lightning:v42.opened,kind:v42.kind,rows:$('v42LBody').querySelectorAll('tr[data-v42item]').length,sldNodes:$('schemeSvg').childElementCount,switchGlyphs:$('schemeSvg').querySelectorAll('[data-switch]').length,bay:$('v42Bay').value}),go:setView,openLightning:()=>{v42.opened=true;v42UpdatePanel();},renderSld:drawScheme,selectBay:id=>{$('v42Bay').value=id;drawScheme();}};
