
'use strict';
/* v5.1: UI & comparison only; source DGS model and v5.0 numerical solver unchanged. */
(function(){
const SC=window.ScenarioController;const Q=id=>document.getElementById(id),esc=s=>h(s),fmtN=x=>Number.isFinite(x)?x.toLocaleString('tr-TR',{maximumFractionDigits:2}):'—';
const UI={metric:'P',comparison:'signed',threshold:20,affectedOnly:false,split:false,analysis:'overview',stationPage:0,stationPageSize:18,stationFid:null};
const RULES={P:{unit:'MW',name:'Aktif güç'},Q:{unit:'MVAr',name:'Reaktif güç'},V:{unit:'kV',name:'Bara gerilimi'},loading:{unit:'yüzde puan',name:'Hat yüklenmesi'}};
function idFor(cls,id){return typeof YTBS_V5_TEST!=='undefined'&&YTBS_V5_TEST.label?YTBS_V5_TEST.label(cls,id):id;}
function key(){return YTBS_V43_TEST.fingerprint()+'|'+SC.revision+'|'+SC.solverVersion;}
function valid(){return !!(active&&v4.base&&v4.base.modelId===active.rid&&v4.scenario&&v4.scenario.modelId===active.rid&&!SC.pending&&!v3.running&&SC.lastCalcKey===key());}
function numResult(set,cls,id,metric,term){let keys=term?[`${cls}|${id}|${metric}|${term}`]:[`${cls}|${id}|${metric}|from`,`${cls}|${id}|${metric}|to`,`${cls}|${id}|${metric}|`];let r=null;for(const k of keys){for(const x of (set?.index?.get(k)||[])){if(x.usable&&(!r||String(x.timestamp)>String(r.timestamp)))r=x;}}return r&&r.usable&&Number.isFinite(Number(r.value))?Number(r.value):null;}
function lineValues(id,met){if(!active)return null;const l=active.lineById(id);if(!l)return null;let a=null,b=null;
 if(met==='loading'){
  const kind=Q('v4Season')?.value||'nominal';
  function val(set){const z=window.LineCapacityEngine?.loadingFromSet(set,l,kind);return z?.percent??null;}
  a=val(v4.base);b=valid()?val(v4.scenario):null;
 }else{a=numResult(v4.base,'ElmLne',id,met,'from');b=valid()?numResult(v4.scenario,'ElmLne',id,met,'from'):null;}
 let delta=a!==null&&b!==null? (UI.comparison==='magnitude'&&met==='P'?Math.abs(b)-Math.abs(a):b-a):null;
 return {id,cls:'ElmLne',a,b,delta,unit:RULES[met].unit,name:idFor('ElmLne',id),line:l};}
function busValues(id){let a=numResult(v4.base,'ElmTerm',id,'V',null),b=valid()?numResult(v4.scenario,'ElmTerm',id,'V',null):null;return{id,cls:'ElmTerm',a,b,delta:a!==null&&b!==null?b-a:null,unit:'kV',name:idFor('ElmTerm',id)};}
function lineList(met=UI.metric){return active?active.lines.map(l=>lineValues(l.FID,met)).filter(Boolean):[];}
function busList(){if(!active||!v4.base)return[];let seen=new Set(),ids=[];for(const r of v4.base.rows||[]){if(r.cls==='ElmTerm'&&r.metric==='V'&&!seen.has(r.id)){seen.add(r.id);ids.push(r.id);}}return ids.map(busValues);}
function affected(list){return list.filter(x=>x.delta!==null&&Number.isFinite(x.delta)&&Math.abs(x.delta)>=UI.threshold).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));}
function initLightningDelta(){
 const pane=Q('v42LightningPanel');if(!pane)return;
 const tabs=pane.querySelector('.v42Ltabs'),btn=document.createElement('button');btn.type='button';btn.id='v51LightningDelta';btn.textContent='Δ Senaryo';btn.setAttribute('aria-label','Elektriksel senaryo değişimleri');tabs.append(btn);
 const box=document.createElement('section');box.id='v51LightningDeltaBody';box.hidden=true;box.className='v51LightningDeltaBody';box.innerHTML='<div class="v51LightningDeltaHead"><label>Değişim türü <select id="v51LightningDeltaMetric"><option value="P">Hat aktif güç ΔP · MW</option><option value="Q">Hat reaktif güç ΔQ · MVAr</option><option value="loading">Hat yüklenme Δ · yüzde puan</option><option value="V">Bara gerilim ΔV · kV</option></select></label><label>Eşik <input id="v51LightningDeltaThreshold" type="number" min="0" step="1" value="20" aria-label="Şimşek paneli değişim eşiği"></label></div><div class="mini" id="v51LightningDeltaStatus" role="status"></div><div id="v51LightningDeltaTable"></div>';
 pane.append(box);
 const originals=[pane.querySelector('.v42Controls'),Q('v42LNote'),pane.querySelector('.v42LScroll')];
 function toggle(on){for(const el of originals)if(el)el.hidden=on;box.hidden=!on;btn.classList.toggle('active',on);if(on){pane.querySelectorAll('[data-v42kind]').forEach(b=>b.classList.remove('active'));renderLightningDelta();}}
 btn.onclick=()=>toggle(box.hidden);for(const b of pane.querySelectorAll('[data-v42kind]'))b.addEventListener('click',()=>toggle(false));
 Q('v51LightningDeltaMetric').onchange=()=>{Q('v51LightningDeltaThreshold').value=Q('v51LightningDeltaMetric').value==='V'?'1':Q('v51LightningDeltaMetric').value==='loading'?'5':'20';renderLightningDelta();};
 Q('v51LightningDeltaThreshold').oninput=renderLightningDelta;
}
function renderLightningDelta(){const box=Q('v51LightningDeltaBody');if(!box||box.hidden)return;
 const out=Q('v51LightningDeltaTable'),st=Q('v51LightningDeltaStatus'),metric=Q('v51LightningDeltaMetric').value;
 if(!active){st.textContent='Önce YTBS JSON modelini yükleyin.';out.replaceChildren();return;}
 if(!valid()){st.textContent=v3.running?'Senaryo hesaplanıyor; sonuç bekleniyor.':SC.pending?'Senaryo değişti; hesap bekliyor.':'Geçerli başlangıç ve senaryo hesabı henüz yok.';out.innerHTML='<p class="mini">Önce hat senaryosunu hesaplayın; eski değerler yeni senaryo olarak gösterilmez.</p>';return;}
 const threshold=Math.max(0,Number(Q('v51LightningDeltaThreshold').value)||0),src=metric==='V'?busList():lineList(metric),rows=src.filter(x=>Number.isFinite(x.delta)&&Math.abs(x.delta)>=threshold).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));
 st.textContent=`${rows.length.toLocaleString('tr-TR')} ekipman · ${RULES[metric].name} · Deneysel hesap · Aynı model ve senaryo revizyonu`;
 out.innerHTML=metricTable(rows,35);bindNav(out);
}
function statusText(){if(!active)return'Model bekleniyor';if(v3.running)return'Hesap sürüyor · Deneysel';if(v4.overrides.size&&SC.pending)return`${v4.overrides.size} hat değiştirildi · Hesap bekliyor`;if(v4.overrides.size&&!valid())return'Senaryo sonucu bulunmuyor · Hesaplanamadı';if(valid())return`${v4.overrides.size} hat değiştirildi · Senaryo hesaplandı · Deneysel`;return'Başlangıç modeli · Deneysel yük akışı';}
function rootControls(){const target=Q('view-map');const bar=document.createElement('div');bar.id='v51Toolbar';bar.className='v51Toolbar';bar.innerHTML=`<div class="v51MainRow"><strong>SONUÇ</strong><button type="button" data-v51view="reference">Başlangıç</button><button type="button" data-v51view="scenario">Senaryo</button><button type="button" data-v51view="delta">Δ Değişim</button><label>Değişim türü <select id="v51Metric"><option value="P">ΔP · MW</option><option value="Q">ΔQ · MVAr</option><option value="V">ΔV · kV</option><option value="loading">ΔYüklenme · yüzde puan</option></select></label><label id="v51DirectionBox">Güç türü <select id="v51Direction"><option value="signed">İşaretli güç</option><option value="magnitude">Güç büyüklüğü</option></select></label><label>Eşik <input id="v51Threshold" type="number" value="20" min="0" step="1" aria-label="Vurgulama eşiği"></label><label class="check"><input id="v51Affected" type="checkbox"> Yalnız etkilenenler</label><button type="button" id="v51SplitToggle">Önce / Sonra</button><button type="button" id="v51Compute" class="primary">Yük akışını hesapla</button><button type="button" id="v51ImpactOpen" class="primary">Etki özeti</button></div><div class="v51StateRow"><span id="v51State" role="status">Model bekleniyor</span><span id="v51Legend">Δ: kırmızı artış · mavi azalış · kesikli servis dışı</span></div>`;
 target.querySelector('.heading').after(bar);
 bar.addEventListener('click',e=>{const b=e.target.closest('[data-v51view]');if(b){const sel=Q('v43ViewSel')||Q('v43View');if(b.dataset.v51view==='delta'&&Q('mapFlow').checked){Q('mapFlow').checked=false;Q('mapFlow').dispatchEvent(new Event('change'));}sel.value=b.dataset.v51view;sel.dispatchEvent(new Event('change',{bubbles:true}));drawMap();refresh();}});
 Q('v51Metric').onchange=e=>{UI.metric=e.target.value;UI.threshold=UI.metric==='V'?1:UI.metric==='Q'?10:UI.metric==='loading'?5:20;Q('v51Threshold').value=UI.threshold;Q('v51DirectionBox').hidden=UI.metric!=='P';refresh();drawMap();};
 Q('v51Direction').onchange=e=>{UI.comparison=e.target.value;refresh();drawMap();};
 Q('v51Threshold').oninput=e=>{UI.threshold=Math.max(0,Number(e.target.value)||0);refresh();drawMap();};
 Q('v51Affected').onchange=e=>{UI.affectedOnly=e.target.checked;drawMap();};
 Q('v51SplitToggle').onclick=()=>{UI.split=!UI.split;Q('v51SplitToggle').classList.toggle('active',UI.split);if(UI.split&&Q('mapMetric').value==='inventory'){Q('mapMetric').value='P';Q('mapMetric').dispatchEvent(new Event('change'));}renderSplit();};
 Q('v51ImpactOpen').onclick=()=>{Q('v51Impact').hidden=!Q('v51Impact').hidden;refresh();};
 Q('v51Compute').onclick=compute;
 const impact=document.createElement('section');impact.id='v51Impact';impact.className='panel v51Impact';impact.hidden=true;impact.innerHTML='<div class="v51ImpactHeading"><strong>⚡ Senaryo etki özeti</strong><button id="v51ImpactClose" aria-label="Etki özetini kapat">✕</button></div><div id="v51ImpactBody">Hesap bekleniyor.</div>';
 Q('view-map').querySelector('.layout')?.before(impact);Q('v51ImpactClose').onclick=()=>impact.hidden=true;
 initLightningDelta();
 const mapWrap=Q('mapWrap');const split=document.createElement('div');split.id='v51Split';split.hidden=true;split.innerHTML='<div class="v51SplitHead">Başlangıç ⟷ Senaryo · kilitli yakınlaştırma</div><div class="v51SplitPlanes"><div><div class="v51SplitLabel">BAŞLANGIÇ</div><canvas id="v51BaseCanvas"></canvas></div><div><div class="v51SplitLabel">SENARYO</div><canvas id="v51ScenarioCanvas"></canvas></div></div><div class="mini">İki yüzey aynı harita kamerası ve kaynak geometrisini kullanır. Deneysel sonuçlar, fiziksel güzergâh veya işletme talimatı değildir.</div>';
 mapWrap.insertAdjacentElement('afterend',split);
 const analysis=Q('view-analysis');const pane=document.createElement('section');pane.className='panel v51Analysis';pane.id='v51Analysis';pane.innerHTML=`<header><h3>Elektriksel analiz çalışma alanı</h3><div><span id="v51AnalysisState">Model bekleniyor</span> <button id="v51AnalysisRun" class="primary" type="button">Yük akışını hesapla</button></div></header><nav id="v51AnalysisTabs" aria-label="Analiz görünümü"><button data-v51analysis="overview">Genel bakış</button><button data-v51analysis="power">Hat P / Q</button><button data-v51analysis="voltage">Bara gerilimi</button><button data-v51analysis="loading">Yüklenme</button><button data-v51analysis="scenario">Senaryo Δ</button><button data-v51analysis="topology">Topoloji</button><button data-v51analysis="quality">Hesap kalitesi</button></nav><div id="v51AnalysisContent" aria-live="polite"></div>`;
 analysis.querySelector('.heading').after(pane);Q('v51AnalysisRun').onclick=compute;const legacy=analysis.querySelector('#modelCapability')?.closest('.panel');if(legacy){const det=document.createElement('details');det.className='v51Legacy';det.innerHTML='<summary>ⓘ Hesap motoru ve model bütünlüğü · Teknik ayrıntılar</summary>';legacy.parentNode.insertBefore(det,legacy);det.append(legacy);}Q('v51AnalysisTabs').onclick=e=>{const b=e.target.closest('[data-v51analysis]');if(b){UI.analysis=b.dataset.v51analysis;renderAnalysis51();}};
 const host=Q('v42SldBar');const sldbar=document.createElement('div');sldbar.id='v51SldBar';sldbar.className='v51SldBar';sldbar.innerHTML='<label>Şema kapsamı <select id="v51SldMode"><option value="general">TM genel görünümü</option><option value="full">TM Node-Breaker bağlantı atlası</option><option value="bay">Fider ayrıntısı</option><option value="regional">Bölgesel TM–hat</option></select></label><label>Fider sayfası <select id="v51StationPage"><option value="0">1</option></select></label><button id="v51SldAll" class="sm">Tüm fiderleri göster</button><span id="v51SldExplain" class="mini">Fiderlerin elektriksel bağlantıları yalnız gerçek StaCubic/ElmCoup uçlarına göre çizilir.</span>';
 host.before(sldbar);Q('v51SldMode').onchange=()=>{UI.stationPage=0;drawScheme();};Q('v51StationPage').onchange=e=>{UI.stationPage=Number(e.target.value)||0;drawScheme();};Q('v51SldAll').onclick=()=>{UI.stationPageSize=UI.stationPageSize===18?10000:18;UI.stationPage=0;Q('v51SldAll').textContent=UI.stationPageSize===18?'Tüm fiderleri göster':'Sayfalı görünüm';drawScheme();};
 Q('v4SldLevel').onchange=()=>{if(Q('v4SldLevel').value==='regional')Q('v51SldMode').value='regional';else Q('v51SldMode').value='general';drawScheme();};
 Q('v42Bay').onchange=()=>{Q('v51SldMode').value='bay';selectedFider=Q('v42Bay').value||null;drawScheme();};
 const oldBadge=Q('v42SldBadge');if(oldBadge)oldBadge.title='Kaynak şebeke modelindeki gerçek terminaller üzerinden bağlantı gösterimi; özgün PowerFactory şalt yerleşimi değildir.';
 document.title='YTBS | Şebeke Görüntüleyici v5.1';document.querySelector('.apphead h1').textContent='YTBS Şebeke Görüntüleyici v5.2';Q('footerRight').textContent='YTBS · Tek HTML · Deneysel Newton AC hesap · v5.2';
}
function compute(){if(!active)return;if(v3.running){SC.cancel();return;}if(v4.overrides.size||v42.switchOverrides.size)SC.run();else Q('runSolver').click();refresh();}
function syncCompare(){const validScenario=valid();for(const b of document.querySelectorAll('[data-v51view]')){b.classList.toggle('active',b.dataset.v51view===SC.viewMode);b.disabled=b.dataset.v51view!=='reference'&&!validScenario;b.title=b.disabled?'Önce geçerli senaryo hesabı oluşturun':'';}
 Q('v51State').textContent=statusText();Q('v51AnalysisState').textContent=statusText();for(const id of ['v51Compute','v51AnalysisRun']){const b=Q(id);if(b){b.disabled=!active;b.textContent=v3.running?'Hesabı iptal et':(v4.overrides.size||v42.switchOverrides.size)?'Senaryoyu hesapla':'Yük akışını hesapla';}}Q('v51Split').hidden=!UI.split;Q('v51SldExplain').textContent=(v42.switchOverrides.size?'⚠ Anahtar pozisyonu sanal şebeke hesabına dahil edilir; sonuçlar deneysel ve doğrulanmamıştır.':'TM şeması: yalnız doğrulanabilen kaynak uçları çizilir; özgün PowerFactory görsel yerleşimi değildir.');}
function refresh(){if(!Q('v51Toolbar'))return;syncCompare();renderImpact();renderLightningDelta();if(currentView==='analysis')renderAnalysis51();if(UI.split&&currentView==='map')renderSplit();}
function metricRow(x,action){return `<tr><td><button class="sm v51Link" data-v51cls="${esc(x.cls)}" data-v51id="${esc(x.id)}" title="Haritada göster">${esc(x.name)}</button>${x.cls==='ElmTerm'?'<small> Bara/düğüm</small>':''}</td><td>${x.a===null?'—':fmtN(x.a)}</td><td>${x.b===null?'—':fmtN(x.b)}</td><td>${x.delta===null?'Hesaplanamadı':(x.delta>0?'+':'')+fmtN(x.delta)} ${esc(x.unit)}</td></tr>`;}
function metricTable(list,max=25){return `<div class="v51TableWrap"><table><thead><tr><th>Ekipman</th><th>Başlangıç</th><th>Senaryo</th><th>Δ</th></tr></thead><tbody>${list.slice(0,max).map(metricRow).join('')||'<tr><td colspan="4">Karşılaştırılabilir sonuç bulunmuyor.</td></tr>'}</tbody></table></div>${list.length>max?`<small>${list.length-max} ek kayıt tabloda gizli; tümü analiz ekranında filtrelenebilir.</small>`:''}`;}
function bindNav(root){root.querySelectorAll('[data-v51id]').forEach(b=>b.onclick=()=>nav(b.dataset.v51cls,b.dataset.v51id));}
function nav(cls,id){if(!active)return;if(cls==='ElmLne'){setView('map');selectLine(id);focusLine(id);if(window.YTBS_V43_TEST)YTBS_V43_TEST.openDrawer(id);}else if(cls==='ElmTerm'){let sid=active.resolveSiteByClass('ElmTerm',id)||active.get('ElmTerm',id)?.fold_id;let site=active.siteById(sid);if(!site){const term=active.get('ElmTerm',id);site=active.siteById(active.resolveSiteByClass('ElmTerm',id,term));}if(site){setView('map');selectSite(site.FID);focusSite(site.FID);}else openEquipment('ElmTerm',id);}}
function renderImpact(){const box=Q('v51ImpactBody');if(!box||Q('v51Impact').hidden)return;
 if(!active){box.textContent='Önce JSON modeli yükleyin.';return;}
 const changes=[...v4.overrides.entries()].map(([id,out])=>{let l=active.lineById(id);return l?`${idFor('ElmLne',id)}: ${out?'servis dışı':'serviste'}`:id;});
 if(!valid()){box.innerHTML=`<div class="v51StatusWarn">${esc(statusText())}. Başlangıç ve senaryo farklı revizyonlardaysa elektriksel değişim hesaplanmaz.</div><div class="mini">${esc(changes.join(' · ')||'Henüz hat değişikliği yok.')}</div>`;return;}
 const ls=affected(lineList(UI.metric==='V'?'P':UI.metric)), bs=affected(busList());const allValid=lineList(UI.metric==='V'?'P':UI.metric).filter(x=>x.delta!==null);
 box.innerHTML=`<div class="v51ImpactKpis"><div><b>${changes.length}</b><small>Değiştirilen hat</small></div><div><b>${ls.length}</b><small>Eşiği aşan hat (${esc(RULES[UI.metric].unit)})</small></div><div><b>${bs.length}</b><small>Eşiği aşan bara gerilimi</small></div><div><b>${allValid.length}</b><small>Karşılaştırılabilir hat</small></div></div><p class="mini">${esc(changes.join(' · '))}</p><h4>En çok değişen hatlar</h4>${metricTable(ls,10)}<h4>En çok değişen baralar</h4>${metricTable(bs,10)}<small>Başlangıç ve senaryo hesapları deneyseldir. Eşik kullanıcı ayarıdır; işletme emniyeti sınırı değildir.</small>`;
 bindNav(box);
}
function drawDelta(){if(!active||mapMode!=='geo'||currentView!=='map'||SC.viewMode!=='delta')return;
 const cv=Q('networkCanvas'),ctx=cv.getContext('2d');let ok=valid();if(!ok)return;
 const data=UI.metric==='V'?affected(busList()):affected(lineList());const visible=selectedVolts(),area=Q('mapArea').value,dpr=Math.min(2,window.devicePixelRatio||1);
 ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);if(UI.affectedOnly){ctx.fillStyle='#102335c9';ctx.fillRect(0,0,mapCam.w,mapCam.h);}
 for(const row of data){if(row.cls==='ElmTerm'){let sid=active.resolveSiteByClass('ElmTerm',row.id),site=active.siteById(sid);if(!site||site.lat==null||site.lon==null||(area&&site.ytmId!==area))continue;const [x,y]=coordsToPx(site.lon,site.lat);if(x<0||y<0||x>mapCam.w||y>mapCam.h)continue;const r=Math.min(19,5+Math.abs(row.delta)/Math.max(.1,UI.threshold+1)*2);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle=row.delta>=0?'#fa655f':'#59a7f6';ctx.lineWidth=2.8;ctx.stroke();continue;}
 const l=row.line;if(!visibleLine(l,visible,area)||v4LineOut(l))continue;const pts=cfg.v4Geometry==='simple'?null:l.coords;let path=pts&&pts.length>=2?pts:(l.siteA?.lat!=null&&l.siteB?.lat!=null?[[l.siteA.lat,l.siteA.lon],[l.siteB.lat,l.siteB.lon]]:null);if(!path)continue;
 const stride=Math.max(1,Math.floor(path.length/120));ctx.beginPath();path.forEach((p,i)=>{if(i%stride!==0&&i!==path.length-1)return;const [x,y]=coordsToPx(p[1],p[0]);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.strokeStyle=row.delta>0?'#fb716c':row.delta<0?'#5eaaf3':'#aab4ba';ctx.globalAlpha=.95;ctx.lineWidth=Math.min(7,2.8+Math.abs(row.delta)/Math.max(5,UI.threshold+1));ctx.stroke();ctx.globalAlpha=1;
 }
 for(const fid of v4.overrides.keys()){let l=active.lineById(fid);if(!l||!visibleLine(l,visible,area))continue;const p=l.coords?.length?l.coords[Math.floor(l.coords.length/2)]:l.siteA?.lat!=null&&l.siteB?.lat!=null?[(l.siteA.lat+l.siteB.lat)/2,(l.siteA.lon+l.siteB.lon)/2]:null;if(!p)continue;const [x,y]=coordsToPx(p[1],p[0]);if(x<0||y<0||x>mapCam.w||y>mapCam.h)continue;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fillStyle='#162c3a';ctx.fill();ctx.strokeStyle='#ffdc7c';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffdc7c';ctx.font='bold 13px system-ui';ctx.fillText('×',x-4,y+4);}
 ctx.restore();}
function paintSplit(canvas){const source=Q('networkCanvas'),rect=canvas.getBoundingClientRect();if(rect.width<40)return;const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const cc=canvas.getContext('2d');cc.setTransform(dpr,0,0,dpr,0,0);cc.drawImage(source,0,0,source.width,source.height,0,0,rect.width,rect.height);}
let splitScheduled=false;
function renderSplit(){const box=Q('v51Split');if(!box)return;box.hidden=!UI.split;if(!UI.split||currentView!=='map'||splitScheduled)return;splitScheduled=true;
 requestAnimationFrame(()=>{splitScheduled=false;if(!UI.split||currentView!=='map')return;
  const was=SC.viewMode,selected=v2.selectedSet;try{
    const b=v4.base&&v4.base.modelId===active?.rid?v4.base:null,sc=valid()?v4.scenario:null;
    if(!b){Q('v51Split').querySelector('.v51SplitHead').textContent='Başlangıç hesabı henüz mevcut değil.';return;}
    Q('v51Split').querySelector('.v51SplitHead').textContent=sc?'Başlangıç ⟷ Senaryo · aynı kamera · ayrı hesap kümeleri':'Başlangıç ⟷ Senaryo hesabı bekliyor';
    v2.selectedSet=b.id;origDrawMap();paintSplit(Q('v51BaseCanvas'));
    if(sc){v2.selectedSet=sc.id;origDrawMap();paintSplit(Q('v51ScenarioCanvas'));}
    else {let c=Q('v51ScenarioCanvas'),r=c.getBoundingClientRect(),ctx=c.getContext('2d');c.width=Math.max(1,r.width);c.height=Math.max(1,r.height);ctx.fillStyle='#152b40';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#ffdda2';ctx.font='14px system-ui';ctx.fillText('Senaryo hesabı bekleniyor',16,38);}
  }finally{v2.selectedSet=selected;SC.viewMode=was;origDrawMap();drawDelta();markOverridden();}
 });}
function renderAnalysis51(){const box=Q('v51AnalysisContent');if(!box)return;Q('v51AnalysisState').textContent=statusText();document.querySelectorAll('[data-v51analysis]').forEach(x=>x.classList.toggle('active',x.dataset.v51analysis===UI.analysis));if(!active){box.innerHTML='<div class="empty">Önce DGS JSON modelini yükleyin.</div>';return;}
 const good=valid(),list=lineList('P'),lineOK=list.filter(x=>x.a!==null).length;
 if(UI.analysis==='overview'){box.innerHTML=`<div class="v51ImpactKpis"><div><b>${nf.format(active.stats.sites)}</b><small>Trafo merkezi</small></div><div><b>${nf.format(active.stats.lines)}</b><small>Hat</small></div><div><b>${nf.format(lineOK)}</b><small>Başlangıç P sonucu</small></div><div><b>${good?'Hazır':SC.pending?'Bekliyor':'Yok'}</b><small>Senaryo karşılaştırması</small></div></div><div class="v51StatusWarn">Deneysel 66 kV+ hesap · Yakınsama, bağımsız PowerFactory doğruluğu değildir.</div>`;}
 else if(UI.analysis==='power'){
 let candidates=list.filter(x=>x.a!==null).slice(0,160),rows=candidates.map(x=>{const p1=numResult(v4.base,'ElmLne',x.id,'P','from'),p2=numResult(v4.base,'ElmLne',x.id,'P','to'),q1=numResult(v4.base,'ElmLne',x.id,'Q','from'),q2=numResult(v4.base,'ElmLne',x.id,'Q','to');return `<tr><td><button class="sm v51Link" data-v51cls="ElmLne" data-v51id="${esc(x.id)}">${esc(x.name)}</button></td>${[p1,p2,q1,q2].map(z=>`<td>${fmtN(z)}</td>`).join('')}</tr>`;});box.innerHTML=`<p class="mini">Başlangıç hesap kümesindeki ilk ${rows.length} hat; karşılaştırmada from/to terminal işaretleri aynen korunur. Ölçüm değil deneysel hesaptır.</p><div class="v51TableWrap"><table><thead><tr><th>Hat</th><th>Başlangıç P (MW)</th><th>Bitiş P (MW)</th><th>Başlangıç Q (MVAr)</th><th>Bitiş Q (MVAr)</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="5">Hesap sonucu yok.</td></tr>'}</tbody></table></div>`;bindNav(box);}
 else if(UI.analysis==='scenario'){const data=affected(lineList('P'));box.innerHTML=`<div class="v51StatusWarn">${esc(statusText())} · Aynı model, geçerli revizyon ve hesap sürümü eşleşmeden Δ üretilmez.</div><h4>En çok değişen hatlar · ΔP (MW)</h4>${good?metricTable(data,100):'<div class="empty">Hesap bekliyor / geçerli karşılaştırma yok.</div>'}<h4>En çok değişen baralar · ΔV (kV)</h4>${good?metricTable(affected(busList()),80):'<div class="empty">Hesaplanamadı.</div>'}`;bindNav(box);}
 else if(UI.analysis==='voltage'){const rows=busList().filter(x=>x.a!==null);box.innerHTML=`<p>${rows.length} hesaplanmış bara/düğüm gerilimi. Gerçek kV değeri nominal gerilimle karıştırılmamalıdır.</p>${metricTable(rows.slice(0,180),180)}`;bindNav(box);}
 else if(UI.analysis==='loading'){const rows=lineList('loading').filter(x=>x.a!==null);box.innerHTML=`<p class="mini">Nominal limit DGS’den, mevsimsel limitler doğrulanmış Excel veya kullanıcı tarafından girilen MVA parametreleridir; resmi TEİAŞ işletme limitleri değildir.</p>${metricTable(rows,180)}`;bindNav(box);}
 else if(UI.analysis==='topology'){box.innerHTML='<div class="mini">Topolojik bağlantı grafı deneysel P/Q/V sonucu değildir. Anahtar senaryosu yerel fider bağlantısını etkiler; mevcut AC motora bütünleşik değildir.</div><div id="v51TopoCount"></div>';try{const r=calculateTopology();Q('v51TopoCount').textContent=JSON.stringify(r?.summary||r?.stats||{},null,2);}catch(e){Q('v51TopoCount').textContent='Topoloji sonucu üretilemedi: '+e.message;}}
 else if(UI.analysis==='quality'){box.innerHTML=`<div class="v51StatusWarn">Deneysel AC-PQ · 66 kV altı indirgeme ve üretim Q kontrolü kısıtlıdır; N-1 veya işletme kararı olarak kullanılmaz.</div><details><summary>Hesap/model teknik ayrıntıları</summary><pre>${esc(JSON.stringify({model:active.name,modelTime:active.date+' '+active.time,solver:v3.solver?.status||'—',solved:v3.solver?.solved,scenarioRevision:SC.revision,validation:v4.validation||'Bağımsız doğrulama yok'},null,2))}</pre></details>`;}
}
function sldFull(){const svg=Q('schemeSvg');svg.replaceChildren();if(!active)return;const site=active.siteById(selectedSite||Q('sldStation').value);if(!site){Q('schemeTitle').textContent='Önce trafo merkezi seçin.';return;}v42EnsureSldIndexes();const bays=active.getEquipmentForSite(site.FID,'ElmBay');if(!bays.length){Q('v42SldBadge').textContent='Bu modelde ayrıntılı fider yok; indirgenmiş bara–dal şeması.';origDrawSchemeGeneral();return;}
 const paged=UI.stationPageSize!==10000;const pageCount=Math.max(1,Math.ceil(bays.length/UI.stationPageSize));UI.stationPage=Math.min(UI.stationPage,pageCount-1);const page=Q('v51StationPage');page.innerHTML=Array.from({length:pageCount},(_,i)=>`<option value="${i}">${i+1} / ${pageCount}</option>`).join('');page.value=String(UI.stationPage);page.closest('label').hidden=!paged;
 const shown=paged?bays.slice(UI.stationPage*UI.stationPageSize,(UI.stationPage+1)*UI.stationPageSize):bays;
 const NS='http://www.w3.org/2000/svg';const E=(type,a,parent=svg)=>{const v=document.createElementNS(NS,type);for(const [k,z]of Object.entries(a||{}))v.setAttribute(k,z);parent.appendChild(v);return v;};const T=(x,y,txt,c='#dfeef2',size=12)=>{let t=E('text',{x,y,fill:c,'font-size':size,'font-family':'system-ui'});t.textContent=txt;return t;};
 const width=1450,col=2,cw=685,hdr=170,cellW=64,baseH=200;let layouts=[],maxHeight=0,missing=0,totalNodes=0,totalSwitches=0,realLinks=0;let siteSwitches=active.getEquipmentForSite(site.FID,'ElmCoup'),byBay=new Map();for(const sw of siteSwitches){let a=byBay.get(sw.fold_id);if(!a)byBay.set(sw.fold_id,a=[]);a.push(sw);}
 for(const bay of shown){const tids=v42.bayIndex.get(bay.FID)||[],sw=byBay.get(bay.FID)||[],nodes=new Map(),edges=[];for(const tid of tids){const node=active.get('ElmTerm',tid);if(node)nodes.set(tid,node);}for(const s of sw){const ta=active.get('StaCubic',s.bus1)?.fold_id||null,tb=active.get('StaCubic',s.bus2)?.fold_id||null;for(const tid of[ta,tb])if(tid&&!nodes.has(tid)){const n=active.get('ElmTerm',tid);if(n)nodes.set(tid,n);}edges.push({s,a:ta,b:tb});if(!ta||!tb)missing++;else realLinks++;}
 totalNodes+=nodes.size;totalSwitches+=edges.length;let nodeIds=[...nodes.keys()].sort(),n=nodeIds.length;let gridRows=Math.ceil(Math.max(1,n)/9),height=Math.max(baseH,118+gridRows*63);layouts.push({bay,nodes,edges,nodeIds,height});maxHeight+=height;}
 let rowY=[hdr,hdr],placements=[];for(let i=0;i<layouts.length;i++){let c=i%2,y=rowY[c],x=40+c*710;rowY[c]+=layouts[i].height+22;placements.push({x,y,...layouts[i]});}const height=Math.max(...rowY)+55;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.style.width=(width*schemeZoom)+'px';svg.style.height=(height*schemeZoom)+'px';svg.style.maxWidth='none';svg.style.display='block';T(24,37,idFor('ElmSite',site.FID)+' · TM gerçek uç bağlantı atlası','#f7e5c1',22);T(24,61,`${bays.length} fider · gösterilen ${shown.length} · ${totalNodes} terminal · ${totalSwitches} anahtar · ${missing} çözülemeyen uç · özgün PF çizimi değildir`,'#a8c6d6',13);
 // Bus elements are station grouping labels only: drawing does not invent a common conductor between disconnected terminals.
 const ss=active.getEquipmentForSite(site.FID,'ElmSubstat').slice(0,15);for(let i=0;i<ss.length;i++){let x=24+(i%5)*280,y=85+Math.floor(i/5)*23;T(x,y,idFor('ElmSubstat',ss[i].FID), '#f4c881',11);}let titleNodes=0;
 for(const v of placements){const {x,y,bay,nodes,edges,nodeIds}=v;E('rect',{x,y,width:685,height:v.height-8,rx:8,fill:'#182e40',stroke:'#45647a'});T(x+14,y+23,idFor('ElmBay',bay.FID), '#b9e4f3',14);T(x+14,y+42,`${nodes.size} terminal · ${edges.length} gerçek anahtar · ${edges.filter(z=>!z.a||!z.b).length} uç çözümsüz`, '#a3b9c8',10);
 const positions=new Map();nodeIds.forEach((id,i)=>{const row=Math.floor(i/9),ix=i%9;positions.set(id,[x+40+ix*70,y+79+row*63]);});
 for(const {s,a,b} of edges){if(!positions.has(a)||!positions.has(b))continue;let [ax,ay]=positions.get(a),[bx,by]=positions.get(b),mx=(ax+bx)/2,my=(ay+by)/2,on=Number(v42.switchOverrides.has(s.FID)?v42.switchOverrides.get(s.FID):s.on_off)===1,k=v42SwitchKind(s);
 E('path',{d:`M${ax},${ay} L${mx},${my} L${bx},${by}`,fill:'none',stroke:'#6d99b2','stroke-width':1.4,'stroke-dasharray':on?'':'4 5'});const g=E('g',{'data-v51switch':s.FID,role:'button',tabindex:0,'aria-label':`${k.name}, ${on?'kapalı':'açık'}, ${idFor('ElmBay',bay.FID)}`,style:'cursor:pointer'});E('rect',{x:mx-10,y:my-10,width:20,height:20,rx:3,fill:'#152638',stroke:on?'#79e0be':'#ffc57e'},g);if(k.code==='cbk'){E('rect',{x:mx-5,y:my-5,width:10,height:10,fill:'none',stroke:'#dcf2eb','stroke-width':1.4},g);}else if(k.code==='dct'){E('line',{x1:mx-6,y1:my+2,x2:mx+5,y2:on?my+2:my-6,stroke:'#dcf2eb','stroke-width':1.8},g);}else E('circle',{cx:mx,cy:my,r:4,fill:'none',stroke:'#ffe0a8'},g);
 g.addEventListener('click',()=>v42SwitchInfo(s,a,b,site,bay));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();v42SwitchInfo(s,a,b,site,bay);}});const ti=E('title',{},g);ti.textContent=`${k.name}: ${s.loc_name} (${s.FID}) · ${a} ↔ ${b} · ${on?'Kapalı':'Açık'}`;}
 for(const [tid,[px,py]]of positions){const term=nodes.get(tid),outer=term?.fold_id!==bay.FID;const gg=E('g',{'data-v51term':tid});if(outer)E('rect',{x:px-13,y:py-5,width:26,height:10,fill:'#e0ad70'},gg);else E('circle',{cx:px,cy:py,r:5,fill:'#7bd5e2'},gg);const name=idFor('ElmTerm',tid);const lab=E('text',{x:px-30,y:py+18,fill:'#c6dce7','font-size':9});lab.textContent=name.slice(0,13);const tt=E('title',{},gg);tt.textContent=`${name} (${tid}) ${outer?'· harici terminal':''}`;gg.style.cursor='pointer';gg.addEventListener('click',()=>openEquipment('ElmTerm',tid));titleNodes++;}
 const g=E('g',{'data-v51bay':bay.FID,role:'button',tabindex:0,style:'cursor:pointer'});E('rect',{x:x+462,y:y+5,width:204,height:30,rx:5,fill:'#245368',stroke:'#5ac0d5'},g);const tt=E('text',{x:x+469,y:y+24,fill:'#e8f8ff','font-size':11},g);tt.textContent='Fider ayrıntısı →';const fun=()=>{Q('v51SldMode').value='bay';Q('v42Bay').value=bay.FID;selectedFider=bay.FID;drawScheme();};g.addEventListener('click',fun);g.addEventListener('keydown',ev=>{if(ev.key==='Enter'){fun();}});
 }
 Q('schemeTitle').textContent=`${idFor('ElmSite',site.FID)} · ${shown.length}/${bays.length} fider · gerçek terminal ve anahtar bağlantıları`;Q('v42SldBadge').textContent=`${totalNodes} terminal / ${totalSwitches} anahtar · ${realLinks} uç çifti · ${missing} çözümsüz`;Q('sldInfo').textContent=`Gösterim kaynağı: ${site.loc_name}. Fiderler ayrı çerçevelerdedir; farklı çerçevelerdeki terminaller sırf yakın çizildi diye elektriksel bağlı sayılmaz. Her çizili anahtar kenarı kaynak modeldeki iki gerçek StaCubic terminalinden oluşturulur. ${bays.length>shown.length?'Tüm fiderler sayfalar arasında listelenir.':''}`;}
function markOverridden(){if(!active||currentView!=='map'||mapMode!=='geo'||!v4.overrides.size)return;const cvs=Q('networkCanvas'),ctx=cvs.getContext('2d'),dpr=Math.min(2,window.devicePixelRatio||1);ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);for(const id of v4.overrides.keys()){const l=active.lineById(id);if(!l||!visibleLine(l,selectedVolts(),Q('mapArea').value))continue;const coords=l.coords?.length?l.coords:null,p=coords?coords[Math.floor(coords.length/2)]:l.siteA?.lat!=null&&l.siteB?.lat!=null?[(l.siteA.lat+l.siteB.lat)/2,(l.siteA.lon+l.siteB.lon)/2]:null;if(!p)continue;const[x,y]=coordsToPx(p[1],p[0]);if(x<0||y<0||x>mapCam.w||y>mapCam.h)continue;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fillStyle='#102438';ctx.fill();ctx.strokeStyle='#ffe192';ctx.lineWidth=2.5;ctx.stroke();ctx.fillStyle='#ffe192';ctx.font='bold 13px system-ui';ctx.fillText('×',x-4,y+4);}ctx.restore();}
const origDrawMap=drawMap;window.drawMap=function(){origDrawMap();drawDelta();markOverridden();if(UI.split&&currentView==='map')renderSplit();};
const origDrawScheme=drawScheme;window.drawScheme=function(){if(currentView==='sld'&&active&&['full','general'].includes(Q('v51SldMode').value)&&Q('v4SldLevel').value!=='regional'){if(Q('v51SldMode').value==='full')return sldFull();Q('v42Bay').value='';selectedFider=null;return origDrawSchemeGeneral();}return origDrawScheme();};
function origDrawSchemeGeneral(){// station summary is existing v4 diagram, not fabricated full Node-Breaker
 const before=Q('v4SldLevel').value,oldMode=mapMode;Q('v4SldLevel').value='station';mapMode='scheme';try{return v4PreviousScheme();}finally{Q('v4SldLevel').value=before;mapMode=oldMode;}}
const origSetView=setView;window.setView=function(v){const out=origSetView(v);if(v==='sld'&&active){if(Q('v51SldMode').value==='full')drawScheme();}if(v==='analysis')renderAnalysis51();if(v==='map')refresh();return out;};
const origSelectLine=selectLine;window.selectLine=function(id){origSelectLine(id);refresh();};
// v4.3 refresh belongs to its private IIFE. The map/analysis wrappers synchronize UI after each rendered transition.
const origDrawAnalysis=renderAnalysis;window.renderAnalysis=function(){origDrawAnalysis();if(currentView==='analysis')renderAnalysis51();};
const origActivate=activateModel;window.activateModel=function(m){let out=origActivate(m);UI.stationPage=0;UI.stationFid=null;refresh();return out;};
const originalStartV51=startV3Solver;window.startV3Solver=async function(){try{return await originalStartV51.apply(this,arguments);}finally{try{refresh();}catch(e){console.warn('v5.1 UI yenileme:',e.message);}}};
rootControls();let lastV51State='';setInterval(()=>{try{let s=[active?.rid,SC.revision,SC.pending,SC.lastCalcKey,v3.running,v4.scenario?.id,SC.viewMode,currentView].join('|');if(s!==lastV51State){lastV51State=s;refresh();}}catch(e){console.warn('v5.1 durum:',e.message);}},450);window.YTBS_V51_TEST={valid,metrics:()=>({...UI}),line:lineValues,bus:busValues,affected,impact:()=>({lines:affected(lineList('P')).length,buses:affected(busList()).length}),sld:()=>({page:UI.stationPage,mode:Q('v51SldMode').value,terminals:Q('schemeSvg').querySelectorAll('[data-v51term]').length,switches:Q('schemeSvg').querySelectorAll('[data-v51switch]').length}),refresh};
})();
